use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "C",
        name: "Carbon",
        atomic_number: 6,
        atomic_mass: 12.011_f64,
        electronegativity: Some(2.55_f64),
        group: Some(14),
        period: 2,
        category: "nonmetal",
        electron_configuration: "1s² 2s² 2p²",
        isotopes: vec![
        Isotope {
            name: "Carbon-8",
            symbol: "⁸C",
            mass_number: 8,
            neutrons: 2,
            atomic_mass: 8.03768_f64,
            half_life: Some(2e-21_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "proton emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-9",
            symbol: "⁹C",
            mass_number: 9,
            neutrons: 3,
            atomic_mass: 9.03104_f64,
            half_life: Some(0.1265_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.6_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta+ proton emission",
                branching_ratio: 0.23_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta+ alpha emission",
                branching_ratio: 0.17_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-10",
            symbol: "¹⁰C",
            mass_number: 10,
            neutrons: 4,
            atomic_mass: 10.01685_f64,
            half_life: Some(19.3009_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-11",
            symbol: "¹¹C",
            mass_number: 11,
            neutrons: 5,
            atomic_mass: 11.011433_f64,
            half_life: Some(20.334_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.998_f64,
                daughter: None,
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.002_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-12",
            symbol: "¹²C",
            mass_number: 12,
            neutrons: 6,
            atomic_mass: 12.0_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.9893_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-13",
            symbol: "¹³C",
            mass_number: 13,
            neutrons: 7,
            atomic_mass: 13.003355_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0107_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Carbon-14",
            symbol: "¹⁴C",
            mass_number: 14,
            neutrons: 8,
            atomic_mass: 14.003242_f64,
            half_life: Some(5730.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Nitrogen-14"),
            },
            ],
            natural_abundance: 1e-12_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-15",
            symbol: "¹⁵C",
            mass_number: 15,
            neutrons: 9,
            atomic_mass: 15.010599_f64,
            half_life: Some(2.449_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Nitrogen-15"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-16",
            symbol: "¹⁶C",
            mass_number: 16,
            neutrons: 10,
            atomic_mass: 16.0147_f64,
            half_life: Some(0.747_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.974_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.026_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-17",
            symbol: "¹⁷C",
            mass_number: 17,
            neutrons: 11,
            atomic_mass: 17.02258_f64,
            half_life: Some(193.0_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.718_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.282_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-18",
            symbol: "¹⁸C",
            mass_number: 18,
            neutrons: 12,
            atomic_mass: 18.02676_f64,
            half_life: Some(92.0_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.684_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.316_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-19",
            symbol: "¹⁹C",
            mass_number: 19,
            neutrons: 13,
            atomic_mass: 19.0348_f64,
            half_life: Some(46.2_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.47_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.53_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-20",
            symbol: "²⁰C",
            mass_number: 20,
            neutrons: 14,
            atomic_mass: 20.04032_f64,
            half_life: Some(16.0_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.72_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.28_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-21",
            symbol: "²¹C",
            mass_number: 21,
            neutrons: 15,
            atomic_mass: 21.04934_f64,
            half_life: Some(30.0_f64),
            half_life_unit: Some("nanoseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Carbon-22",
            symbol: "²²C",
            mass_number: 22,
            neutrons: 16,
            atomic_mass: 22.0572_f64,
            half_life: Some(6.2_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
