use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "H",
        name: "Hydrogen",
        atomic_number: 1,
        atomic_mass: 1.008_f64,
        electronegativity: Some(2.2_f64),
        group: Some(1),
        period: 1,
        category: "nonmetal",
        electron_configuration: "1s¹",
        isotopes: vec![
        Isotope {
            name: "Protium",
            symbol: "¹H",
            mass_number: 1,
            neutrons: 0,
            atomic_mass: 1.007825_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.999885_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Deuterium",
            symbol: "²H",
            mass_number: 2,
            neutrons: 1,
            atomic_mass: 2.014102_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.000115_f64,
            nuclear_spin: Some("1+"),
        },
        Isotope {
            name: "Tritium",
            symbol: "³H",
            mass_number: 3,
            neutrons: 2,
            atomic_mass: 3.016049_f64,
            half_life: Some(12.32_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Helium-3"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Hydrogen-4",
            symbol: "⁴H",
            mass_number: 4,
            neutrons: 3,
            atomic_mass: 4.02643_f64,
            half_life: Some(1.39e-22_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Hydrogen-5",
            symbol: "⁵H",
            mass_number: 5,
            neutrons: 4,
            atomic_mass: 5.03531_f64,
            half_life: Some(9.1e-22_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Hydrogen-6",
            symbol: "⁶H",
            mass_number: 6,
            neutrons: 5,
            atomic_mass: 6.04496_f64,
            half_life: Some(2.9e-22_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "triple neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Hydrogen-7",
            symbol: "⁷H",
            mass_number: 7,
            neutrons: 6,
            atomic_mass: 7.05275_f64,
            half_life: Some(2.3e-23_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
