use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "N",
        name: "Nitrogen",
        atomic_number: 7,
        atomic_mass: 14.007_f64,
        electronegativity: Some(3.04_f64),
        group: Some(15),
        period: 2,
        category: "nonmetal",
        electron_configuration: "1s² 2s² 2p³",
        isotopes: vec![
        Isotope {
            name: "Nitrogen-10",
            symbol: "¹⁰N",
            mass_number: 10,
            neutrons: 3,
            atomic_mass: 10.04165_f64,
            half_life: Some(2e-22_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "proton emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Nitrogen-11",
            symbol: "¹¹N",
            mass_number: 11,
            neutrons: 4,
            atomic_mass: 11.02609_f64,
            half_life: Some(5.9e-22_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "proton emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Nitrogen-12",
            symbol: "¹²N",
            mass_number: 12,
            neutrons: 5,
            atomic_mass: 12.018613_f64,
            half_life: Some(11.0_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.965_f64,
                daughter: Some("Carbon-12"),
            },
            DecayMode {
                mode: "beta+ alpha emission",
                branching_ratio: 0.035_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Nitrogen-13",
            symbol: "¹³N",
            mass_number: 13,
            neutrons: 6,
            atomic_mass: 13.005739_f64,
            half_life: Some(9.965_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Carbon-13"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Nitrogen-14",
            symbol: "¹⁴N",
            mass_number: 14,
            neutrons: 7,
            atomic_mass: 14.003074_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.99636_f64,
            nuclear_spin: Some("1+"),
        },
        Isotope {
            name: "Nitrogen-15",
            symbol: "¹⁵N",
            mass_number: 15,
            neutrons: 8,
            atomic_mass: 15.000109_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00364_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Nitrogen-16",
            symbol: "¹⁶N",
            mass_number: 16,
            neutrons: 9,
            atomic_mass: 16.006102_f64,
            half_life: Some(7.13_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.999_f64,
                daughter: Some("Oxygen-16"),
            },
            DecayMode {
                mode: "beta- alpha emission",
                branching_ratio: 0.001_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Nitrogen-17",
            symbol: "¹⁷N",
            mass_number: 17,
            neutrons: 10,
            atomic_mass: 17.00845_f64,
            half_life: Some(4.173_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.951_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.049_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Nitrogen-18",
            symbol: "¹⁸N",
            mass_number: 18,
            neutrons: 11,
            atomic_mass: 18.01408_f64,
            half_life: Some(619.0_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.77_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- alpha emission",
                branching_ratio: 0.12_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.11_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Nitrogen-19",
            symbol: "¹⁹N",
            mass_number: 19,
            neutrons: 12,
            atomic_mass: 19.01703_f64,
            half_life: Some(336.0_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.58_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.42_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Nitrogen-23",
            symbol: "²³N",
            mass_number: 23,
            neutrons: 16,
            atomic_mass: 23.04122_f64,
            half_life: Some(13.9_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
