use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "O",
        name: "Oxygen",
        atomic_number: 8,
        atomic_mass: 15.999_f64,
        electronegativity: Some(3.44_f64),
        group: Some(16),
        period: 2,
        category: "nonmetal",
        electron_configuration: "1s² 2s² 2p⁴",
        isotopes: vec![
        Isotope {
            name: "Oxygen-12",
            symbol: "¹²O",
            mass_number: 12,
            neutrons: 4,
            atomic_mass: 12.0344_f64,
            half_life: Some(5.8e-22_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "two-proton emission",
                branching_ratio: 0.6_f64,
                daughter: None,
            },
            DecayMode {
                mode: "proton emission",
                branching_ratio: 0.4_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Oxygen-13",
            symbol: "¹³O",
            mass_number: 13,
            neutrons: 5,
            atomic_mass: 13.02481_f64,
            half_life: Some(8.58_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.898_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta+ proton emission",
                branching_ratio: 0.102_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Oxygen-14",
            symbol: "¹⁴O",
            mass_number: 14,
            neutrons: 6,
            atomic_mass: 14.008596_f64,
            half_life: Some(70.62_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Nitrogen-14"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Oxygen-15",
            symbol: "¹⁵O",
            mass_number: 15,
            neutrons: 7,
            atomic_mass: 15.003066_f64,
            half_life: Some(122.24_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Nitrogen-15"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Oxygen-16",
            symbol: "¹⁶O",
            mass_number: 16,
            neutrons: 8,
            atomic_mass: 15.994915_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.99757_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Oxygen-17",
            symbol: "¹⁷O",
            mass_number: 17,
            neutrons: 9,
            atomic_mass: 16.999132_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00038_f64,
            nuclear_spin: Some("5/2+"),
        },
        Isotope {
            name: "Oxygen-18",
            symbol: "¹⁸O",
            mass_number: 18,
            neutrons: 10,
            atomic_mass: 17.999161_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00205_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Oxygen-19",
            symbol: "¹⁹O",
            mass_number: 19,
            neutrons: 11,
            atomic_mass: 19.00358_f64,
            half_life: Some(26.464_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Fluorine-19"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Oxygen-20",
            symbol: "²⁰O",
            mass_number: 20,
            neutrons: 12,
            atomic_mass: 20.00408_f64,
            half_life: Some(13.51_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Fluorine-20"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Oxygen-21",
            symbol: "²¹O",
            mass_number: 21,
            neutrons: 13,
            atomic_mass: 21.00866_f64,
            half_life: Some(3.42_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Oxygen-22",
            symbol: "²²O",
            mass_number: 22,
            neutrons: 14,
            atomic_mass: 22.01_f64,
            half_life: Some(2.25_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.78_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.22_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Oxygen-24",
            symbol: "²⁴O",
            mass_number: 24,
            neutrons: 16,
            atomic_mass: 24.01986_f64,
            half_life: Some(65.0_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.42_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.58_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
