use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Se",
        name: "Selenium",
        atomic_number: 34,
        atomic_mass: 78.971_f64,
        electronegativity: Some(2.55_f64),
        group: Some(16),
        period: 4,
        category: "nonmetal",
        electron_configuration: "[Ar] 3d¹⁰ 4s² 4p⁴",
        isotopes: vec![
        Isotope {
            name: "Selenium-74",
            symbol: "⁷⁴Se",
            mass_number: 74,
            neutrons: 40,
            atomic_mass: 73.922477_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0089_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Selenium-75",
            symbol: "⁷⁵Se",
            mass_number: 75,
            neutrons: 41,
            atomic_mass: 74.922524_f64,
            half_life: Some(119.779_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Arsenic-75"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Selenium-76",
            symbol: "⁷⁶Se",
            mass_number: 76,
            neutrons: 42,
            atomic_mass: 75.919214_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0937_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Selenium-77",
            symbol: "⁷⁷Se",
            mass_number: 77,
            neutrons: 43,
            atomic_mass: 76.919914_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0763_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Selenium-78",
            symbol: "⁷⁸Se",
            mass_number: 78,
            neutrons: 44,
            atomic_mass: 77.91731_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2377_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Selenium-79",
            symbol: "⁷⁹Se",
            mass_number: 79,
            neutrons: 45,
            atomic_mass: 78.9185_f64,
            half_life: Some(327000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Bromine-79"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Selenium-80",
            symbol: "⁸⁰Se",
            mass_number: 80,
            neutrons: 46,
            atomic_mass: 79.916522_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.4961_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Selenium-82",
            symbol: "⁸²Se",
            mass_number: 82,
            neutrons: 48,
            atomic_mass: 81.9167_f64,
            half_life: Some(8.7e+19_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double beta- (double electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Krypton-82"),
            },
            ],
            natural_abundance: 0.0873_f64,
            nuclear_spin: None,
        },
        ],
    }
}
