use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "S",
        name: "Sulfur",
        atomic_number: 16,
        atomic_mass: 32.06_f64,
        electronegativity: Some(2.58_f64),
        group: Some(16),
        period: 3,
        category: "nonmetal",
        electron_configuration: "[Ne] 3s² 3p⁴",
        isotopes: vec![
        Isotope {
            name: "Sulfur-32",
            symbol: "³²S",
            mass_number: 32,
            neutrons: 16,
            atomic_mass: 31.972071_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.9499_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Sulfur-33",
            symbol: "³³S",
            mass_number: 33,
            neutrons: 17,
            atomic_mass: 32.971459_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0075_f64,
            nuclear_spin: Some("3/2+"),
        },
        Isotope {
            name: "Sulfur-34",
            symbol: "³⁴S",
            mass_number: 34,
            neutrons: 18,
            atomic_mass: 33.967867_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0425_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Sulfur-35",
            symbol: "³⁵S",
            mass_number: 35,
            neutrons: 19,
            atomic_mass: 34.969032_f64,
            half_life: Some(87.37_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Chlorine-35"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Sulfur-36",
            symbol: "³⁶S",
            mass_number: 36,
            neutrons: 20,
            atomic_mass: 35.967081_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0001_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Sulfur-38",
            symbol: "³⁸S",
            mass_number: 38,
            neutrons: 22,
            atomic_mass: 37.97116_f64,
            half_life: Some(170.3_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Chlorine-38"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
