use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "At",
        name: "Astatine",
        atomic_number: 85,
        atomic_mass: 210.0_f64,
        electronegativity: Some(2.2_f64),
        group: Some(17),
        period: 6,
        category: "halogen",
        electron_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
        isotopes: vec![
        Isotope {
            name: "Astatine-205",
            symbol: "²⁰⁵At",
            mass_number: 205,
            neutrons: 120,
            atomic_mass: 204.98607_f64,
            half_life: Some(26.2_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 0.1_f64,
                daughter: None,
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.9_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Astatine-207",
            symbol: "²⁰⁷At",
            mass_number: 207,
            neutrons: 122,
            atomic_mass: 206.98578_f64,
            half_life: Some(1.8_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.895_f64,
                daughter: None,
            },
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 0.105_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Astatine-209",
            symbol: "²⁰⁹At",
            mass_number: 209,
            neutrons: 124,
            atomic_mass: 208.98617_f64,
            half_life: Some(5.41_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.958_f64,
                daughter: None,
            },
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 0.042_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Astatine-210",
            symbol: "²¹⁰At",
            mass_number: 210,
            neutrons: 125,
            atomic_mass: 209.98715_f64,
            half_life: Some(8.1_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.998_f64,
                daughter: None,
            },
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 0.002_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Astatine-211",
            symbol: "²¹¹At",
            mass_number: 211,
            neutrons: 126,
            atomic_mass: 210.9875_f64,
            half_life: Some(7.214_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.583_f64,
                daughter: Some("Polonium-211"),
            },
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 0.417_f64,
                daughter: Some("Bismuth-207"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Astatine-215",
            symbol: "²¹⁵At",
            mass_number: 215,
            neutrons: 130,
            atomic_mass: 214.99865_f64,
            half_life: Some(0.1_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 1.0_f64,
                daughter: Some("Bismuth-211"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Astatine-217",
            symbol: "²¹⁷At",
            mass_number: 217,
            neutrons: 132,
            atomic_mass: 217.00472_f64,
            half_life: Some(32.3_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 0.998_f64,
                daughter: Some("Bismuth-213"),
            },
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.002_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Astatine-218",
            symbol: "²¹⁸At",
            mass_number: 218,
            neutrons: 133,
            atomic_mass: 218.00869_f64,
            half_life: Some(1.5_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 0.999_f64,
                daughter: Some("Bismuth-214"),
            },
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.001_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
