use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Br",
        name: "Bromine",
        atomic_number: 35,
        atomic_mass: 79.904_f64,
        electronegativity: Some(2.96_f64),
        group: Some(17),
        period: 4,
        category: "halogen",
        electron_configuration: "[Ar] 3d¹⁰ 4s² 4p⁵",
        isotopes: vec![
        Isotope {
            name: "Bromine-75",
            symbol: "⁷⁵Br",
            mass_number: 75,
            neutrons: 40,
            atomic_mass: 74.96859_f64,
            half_life: Some(96.7_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Selenium-75"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Bromine-76",
            symbol: "⁷⁶Br",
            mass_number: 76,
            neutrons: 41,
            atomic_mass: 75.96854_f64,
            half_life: Some(16.2_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Selenium-76"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Bromine-77",
            symbol: "⁷⁷Br",
            mass_number: 77,
            neutrons: 42,
            atomic_mass: 76.92138_f64,
            half_life: Some(57.04_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.994_f64,
                daughter: Some("Selenium-77"),
            },
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.006_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Bromine-79",
            symbol: "⁷⁹Br",
            mass_number: 79,
            neutrons: 44,
            atomic_mass: 78.918338_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.5069_f64,
            nuclear_spin: Some("3/2-"),
        },
        Isotope {
            name: "Bromine-80",
            symbol: "⁸⁰Br",
            mass_number: 80,
            neutrons: 45,
            atomic_mass: 79.91853_f64,
            half_life: Some(17.68_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.917_f64,
                daughter: Some("Krypton-80"),
            },
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.028_f64,
                daughter: None,
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.055_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Bromine-81",
            symbol: "⁸¹Br",
            mass_number: 81,
            neutrons: 46,
            atomic_mass: 80.916291_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.4931_f64,
            nuclear_spin: Some("3/2-"),
        },
        Isotope {
            name: "Bromine-82",
            symbol: "⁸²Br",
            mass_number: 82,
            neutrons: 47,
            atomic_mass: 81.916805_f64,
            half_life: Some(35.282_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Krypton-82"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Bromine-83",
            symbol: "⁸³Br",
            mass_number: 83,
            neutrons: 48,
            atomic_mass: 82.91518_f64,
            half_life: Some(2.4_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Krypton-83"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Bromine-84",
            symbol: "⁸⁴Br",
            mass_number: 84,
            neutrons: 49,
            atomic_mass: 83.91648_f64,
            half_life: Some(31.8_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
