use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Cl",
        name: "Chlorine",
        atomic_number: 17,
        atomic_mass: 35.45_f64,
        electronegativity: Some(3.16_f64),
        group: Some(17),
        period: 3,
        category: "halogen",
        electron_configuration: "[Ne] 3s² 3p⁵",
        isotopes: vec![
        Isotope {
            name: "Chlorine-32",
            symbol: "³²Cl",
            mass_number: 32,
            neutrons: 15,
            atomic_mass: 31.98569_f64,
            half_life: Some(298.0_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Sulfur-32"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Chlorine-33",
            symbol: "³³Cl",
            mass_number: 33,
            neutrons: 16,
            atomic_mass: 32.97745_f64,
            half_life: Some(2.5038_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Sulfur-33"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Chlorine-34",
            symbol: "³⁴Cl",
            mass_number: 34,
            neutrons: 17,
            atomic_mass: 33.97376_f64,
            half_life: Some(1.5264_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Sulfur-34"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Chlorine-35",
            symbol: "³⁵Cl",
            mass_number: 35,
            neutrons: 18,
            atomic_mass: 34.968853_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.7576_f64,
            nuclear_spin: Some("3/2+"),
        },
        Isotope {
            name: "Chlorine-36",
            symbol: "³⁶Cl",
            mass_number: 36,
            neutrons: 19,
            atomic_mass: 35.968307_f64,
            half_life: Some(301000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.981_f64,
                daughter: Some("Argon-36"),
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.019_f64,
                daughter: Some("Sulfur-36"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Chlorine-37",
            symbol: "³⁷Cl",
            mass_number: 37,
            neutrons: 20,
            atomic_mass: 36.965903_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2424_f64,
            nuclear_spin: Some("3/2+"),
        },
        Isotope {
            name: "Chlorine-38",
            symbol: "³⁸Cl",
            mass_number: 38,
            neutrons: 21,
            atomic_mass: 37.968011_f64,
            half_life: Some(37.24_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Argon-38"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Chlorine-39",
            symbol: "³⁹Cl",
            mass_number: 39,
            neutrons: 22,
            atomic_mass: 38.96801_f64,
            half_life: Some(55.6_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Argon-39"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Chlorine-40",
            symbol: "⁴⁰Cl",
            mass_number: 40,
            neutrons: 23,
            atomic_mass: 39.97042_f64,
            half_life: Some(1.35_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
