use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "F",
        name: "Fluorine",
        atomic_number: 9,
        atomic_mass: 18.998403_f64,
        electronegativity: Some(3.98_f64),
        group: Some(17),
        period: 2,
        category: "halogen",
        electron_configuration: "1s² 2s² 2p⁵",
        isotopes: vec![
        Isotope {
            name: "Fluorine-14",
            symbol: "¹⁴F",
            mass_number: 14,
            neutrons: 5,
            atomic_mass: 14.03506_f64,
            half_life: Some(5e-22_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "proton emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Fluorine-15",
            symbol: "¹⁵F",
            mass_number: 15,
            neutrons: 6,
            atomic_mass: 15.01801_f64,
            half_life: Some(4.1e-22_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "proton emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Fluorine-17",
            symbol: "¹⁷F",
            mass_number: 17,
            neutrons: 8,
            atomic_mass: 17.002095_f64,
            half_life: Some(64.49_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Oxygen-17"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Fluorine-18",
            symbol: "¹⁸F",
            mass_number: 18,
            neutrons: 9,
            atomic_mass: 18.000938_f64,
            half_life: Some(109.77_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.967_f64,
                daughter: Some("Oxygen-18"),
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.033_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Fluorine-19",
            symbol: "¹⁹F",
            mass_number: 19,
            neutrons: 10,
            atomic_mass: 18.998403_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 1.0_f64,
            nuclear_spin: Some("1/2+"),
        },
        Isotope {
            name: "Fluorine-20",
            symbol: "²⁰F",
            mass_number: 20,
            neutrons: 11,
            atomic_mass: 19.999981_f64,
            half_life: Some(11.163_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Neon-20"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Fluorine-21",
            symbol: "²¹F",
            mass_number: 21,
            neutrons: 12,
            atomic_mass: 20.99995_f64,
            half_life: Some(4.158_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Neon-21"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Fluorine-22",
            symbol: "²²F",
            mass_number: 22,
            neutrons: 13,
            atomic_mass: 22.003_f64,
            half_life: Some(4.23_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.89_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.11_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Fluorine-29",
            symbol: "²⁹F",
            mass_number: 29,
            neutrons: 20,
            atomic_mass: 29.04326_f64,
            half_life: Some(2.6_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
