use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "I",
        name: "Iodine",
        atomic_number: 53,
        atomic_mass: 126.90447_f64,
        electronegativity: Some(2.66_f64),
        group: Some(17),
        period: 5,
        category: "halogen",
        electron_configuration: "[Kr] 4d¹⁰ 5s² 5p⁵",
        isotopes: vec![
        Isotope {
            name: "Iodine-123",
            symbol: "¹²³I",
            mass_number: 123,
            neutrons: 70,
            atomic_mass: 122.905598_f64,
            half_life: Some(13.2235_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Tellurium-123"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Iodine-124",
            symbol: "¹²⁴I",
            mass_number: 124,
            neutrons: 71,
            atomic_mass: 123.90621_f64,
            half_life: Some(4.176_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.228_f64,
                daughter: None,
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.772_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Iodine-125",
            symbol: "¹²⁵I",
            mass_number: 125,
            neutrons: 72,
            atomic_mass: 124.90463_f64,
            half_life: Some(59.4_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Tellurium-125"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Iodine-126",
            symbol: "¹²⁶I",
            mass_number: 126,
            neutrons: 73,
            atomic_mass: 125.905624_f64,
            half_life: Some(12.93_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.474_f64,
                daughter: None,
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.474_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.052_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Iodine-127",
            symbol: "¹²⁷I",
            mass_number: 127,
            neutrons: 74,
            atomic_mass: 126.904473_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 1.0_f64,
            nuclear_spin: Some("5/2+"),
        },
        Isotope {
            name: "Iodine-128",
            symbol: "¹²⁸I",
            mass_number: 128,
            neutrons: 75,
            atomic_mass: 127.905809_f64,
            half_life: Some(24.99_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.935_f64,
                daughter: Some("Xenon-128"),
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.065_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Iodine-129",
            symbol: "¹²⁹I",
            mass_number: 129,
            neutrons: 76,
            atomic_mass: 128.904988_f64,
            half_life: Some(15700000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Xenon-129"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Iodine-131",
            symbol: "¹³¹I",
            mass_number: 131,
            neutrons: 78,
            atomic_mass: 130.906125_f64,
            half_life: Some(8.0252_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Xenon-131"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Iodine-132",
            symbol: "¹³²I",
            mass_number: 132,
            neutrons: 79,
            atomic_mass: 131.907997_f64,
            half_life: Some(2.295_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Xenon-132"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Iodine-133",
            symbol: "¹³³I",
            mass_number: 133,
            neutrons: 80,
            atomic_mass: 132.90781_f64,
            half_life: Some(20.83_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Xenon-133"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Iodine-135",
            symbol: "¹³⁵I",
            mass_number: 135,
            neutrons: 82,
            atomic_mass: 134.91005_f64,
            half_life: Some(6.57_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Xenon-135"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
