use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Ar",
        name: "Argon",
        atomic_number: 18,
        atomic_mass: 39.948_f64,
        electronegativity: None,
        group: Some(18),
        period: 3,
        category: "noble gas",
        electron_configuration: "[Ne] 3s² 3p⁶",
        isotopes: vec![
        Isotope {
            name: "Argon-33",
            symbol: "³³Ar",
            mass_number: 33,
            neutrons: 15,
            atomic_mass: 32.98993_f64,
            half_life: Some(173.0_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Chlorine-33"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Argon-35",
            symbol: "³⁵Ar",
            mass_number: 35,
            neutrons: 17,
            atomic_mass: 34.97526_f64,
            half_life: Some(1.7756_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Chlorine-35"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Argon-36",
            symbol: "³⁶Ar",
            mass_number: 36,
            neutrons: 18,
            atomic_mass: 35.967546_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.003336_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Argon-37",
            symbol: "³⁷Ar",
            mass_number: 37,
            neutrons: 19,
            atomic_mass: 36.966776_f64,
            half_life: Some(35.04_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Chlorine-37"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Argon-38",
            symbol: "³⁸Ar",
            mass_number: 38,
            neutrons: 20,
            atomic_mass: 37.962732_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.000629_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Argon-39",
            symbol: "³⁹Ar",
            mass_number: 39,
            neutrons: 21,
            atomic_mass: 38.964313_f64,
            half_life: Some(268.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Potassium-39"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Argon-40",
            symbol: "⁴⁰Ar",
            mass_number: 40,
            neutrons: 22,
            atomic_mass: 39.962383_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.996035_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Argon-41",
            symbol: "⁴¹Ar",
            mass_number: 41,
            neutrons: 23,
            atomic_mass: 40.964501_f64,
            half_life: Some(109.61_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Potassium-41"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Argon-42",
            symbol: "⁴²Ar",
            mass_number: 42,
            neutrons: 24,
            atomic_mass: 41.96305_f64,
            half_life: Some(32.9_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Potassium-42"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
