use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "He",
        name: "Helium",
        atomic_number: 2,
        atomic_mass: 4.002602_f64,
        electronegativity: None,
        group: Some(18),
        period: 1,
        category: "noble gas",
        electron_configuration: "1s²",
        isotopes: vec![
        Isotope {
            name: "Helium-3",
            symbol: "³He",
            mass_number: 3,
            neutrons: 1,
            atomic_mass: 3.016029_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 1.34e-06_f64,
            nuclear_spin: Some("1/2+"),
        },
        Isotope {
            name: "Helium-4",
            symbol: "⁴He",
            mass_number: 4,
            neutrons: 2,
            atomic_mass: 4.002603_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.99999866_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Helium-5",
            symbol: "⁵He",
            mass_number: 5,
            neutrons: 3,
            atomic_mass: 5.01222_f64,
            half_life: Some(7.6e-22_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Helium-6",
            symbol: "⁶He",
            mass_number: 6,
            neutrons: 4,
            atomic_mass: 6.018886_f64,
            half_life: Some(806.92_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Lithium-6"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Helium-7",
            symbol: "⁷He",
            mass_number: 7,
            neutrons: 5,
            atomic_mass: 7.02803_f64,
            half_life: Some(2.9e-21_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Helium-8",
            symbol: "⁸He",
            mass_number: 8,
            neutrons: 6,
            atomic_mass: 8.03392_f64,
            half_life: Some(119.1_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.84_f64,
                daughter: Some("Lithium-8"),
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.16_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Helium-9",
            symbol: "⁹He",
            mass_number: 9,
            neutrons: 7,
            atomic_mass: 9.04395_f64,
            half_life: Some(7e-21_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Helium-10",
            symbol: "¹⁰He",
            mass_number: 10,
            neutrons: 8,
            atomic_mass: 10.0524_f64,
            half_life: Some(2.7e-21_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
