use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Kr",
        name: "Krypton",
        atomic_number: 36,
        atomic_mass: 83.798_f64,
        electronegativity: Some(3.0_f64),
        group: Some(18),
        period: 4,
        category: "noble gas",
        electron_configuration: "[Ar] 3d¹⁰ 4s² 4p⁶",
        isotopes: vec![
        Isotope {
            name: "Krypton-78",
            symbol: "⁷⁸Kr",
            mass_number: 78,
            neutrons: 42,
            atomic_mass: 77.920365_f64,
            half_life: Some(9.2e+21_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Selenium-78"),
            },
            ],
            natural_abundance: 0.00355_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Krypton-80",
            symbol: "⁸⁰Kr",
            mass_number: 80,
            neutrons: 44,
            atomic_mass: 79.916378_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.02286_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Krypton-81",
            symbol: "⁸¹Kr",
            mass_number: 81,
            neutrons: 45,
            atomic_mass: 80.916592_f64,
            half_life: Some(229000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Bromine-81"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Krypton-82",
            symbol: "⁸²Kr",
            mass_number: 82,
            neutrons: 46,
            atomic_mass: 81.913484_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.11593_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Krypton-83",
            symbol: "⁸³Kr",
            mass_number: 83,
            neutrons: 47,
            atomic_mass: 82.914136_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.115_f64,
            nuclear_spin: Some("9/2+"),
        },
        Isotope {
            name: "Krypton-84",
            symbol: "⁸⁴Kr",
            mass_number: 84,
            neutrons: 48,
            atomic_mass: 83.911507_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.56987_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Krypton-85",
            symbol: "⁸⁵Kr",
            mass_number: 85,
            neutrons: 49,
            atomic_mass: 84.912527_f64,
            half_life: Some(10.756_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Rubidium-85"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Krypton-86",
            symbol: "⁸⁶Kr",
            mass_number: 86,
            neutrons: 50,
            atomic_mass: 85.910611_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.17279_f64,
            nuclear_spin: Some("0+"),
        },
        ],
    }
}
