use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Ne",
        name: "Neon",
        atomic_number: 10,
        atomic_mass: 20.1797_f64,
        electronegativity: None,
        group: Some(18),
        period: 2,
        category: "noble gas",
        electron_configuration: "1s² 2s² 2p⁶",
        isotopes: vec![
        Isotope {
            name: "Neon-17",
            symbol: "¹⁷Ne",
            mass_number: 17,
            neutrons: 7,
            atomic_mass: 17.01772_f64,
            half_life: Some(109.2_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.955_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta+ proton emission",
                branching_ratio: 0.04_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta+ alpha emission",
                branching_ratio: 0.005_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Neon-18",
            symbol: "¹⁸Ne",
            mass_number: 18,
            neutrons: 8,
            atomic_mass: 18.00571_f64,
            half_life: Some(1.6672_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Fluorine-18"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Neon-19",
            symbol: "¹⁹Ne",
            mass_number: 19,
            neutrons: 9,
            atomic_mass: 19.00188_f64,
            half_life: Some(17.274_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Fluorine-19"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Neon-20",
            symbol: "²⁰Ne",
            mass_number: 20,
            neutrons: 10,
            atomic_mass: 19.99244_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.9048_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Neon-21",
            symbol: "²¹Ne",
            mass_number: 21,
            neutrons: 11,
            atomic_mass: 20.993847_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0027_f64,
            nuclear_spin: Some("3/2+"),
        },
        Isotope {
            name: "Neon-22",
            symbol: "²²Ne",
            mass_number: 22,
            neutrons: 12,
            atomic_mass: 21.991386_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0925_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Neon-23",
            symbol: "²³Ne",
            mass_number: 23,
            neutrons: 13,
            atomic_mass: 22.994467_f64,
            half_life: Some(37.15_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Sodium-23"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Neon-24",
            symbol: "²⁴Ne",
            mass_number: 24,
            neutrons: 14,
            atomic_mass: 23.993615_f64,
            half_life: Some(3.38_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Sodium-24"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
