use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Rn",
        name: "Radon",
        atomic_number: 86,
        atomic_mass: 222.0_f64,
        electronegativity: Some(2.2_f64),
        group: Some(18),
        period: 6,
        category: "noble gas",
        electron_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
        isotopes: vec![
        Isotope {
            name: "Radon-210",
            symbol: "²¹⁰Rn",
            mass_number: 210,
            neutrons: 124,
            atomic_mass: 209.9897_f64,
            half_life: Some(2.4_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 0.96_f64,
                daughter: Some("Polonium-206"),
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.04_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Radon-211",
            symbol: "²¹¹Rn",
            mass_number: 211,
            neutrons: 125,
            atomic_mass: 210.9906_f64,
            half_life: Some(14.6_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 0.728_f64,
                daughter: Some("Polonium-207"),
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.272_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Radon-219",
            symbol: "²¹⁹Rn",
            mass_number: 219,
            neutrons: 133,
            atomic_mass: 219.00948_f64,
            half_life: Some(3.96_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 1.0_f64,
                daughter: Some("Polonium-215"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Radon-220",
            symbol: "²²⁰Rn",
            mass_number: 220,
            neutrons: 134,
            atomic_mass: 220.01139_f64,
            half_life: Some(55.6_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 1.0_f64,
                daughter: Some("Polonium-216"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Radon-222",
            symbol: "²²²Rn",
            mass_number: 222,
            neutrons: 136,
            atomic_mass: 222.01758_f64,
            half_life: Some(3.8235_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 1.0_f64,
                daughter: Some("Polonium-218"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Radon-224",
            symbol: "²²⁴Rn",
            mass_number: 224,
            neutrons: 138,
            atomic_mass: 224.02409_f64,
            half_life: Some(107.0_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Radon-226",
            symbol: "²²⁶Rn",
            mass_number: 226,
            neutrons: 140,
            atomic_mass: 226.03089_f64,
            half_life: Some(7.4_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
