use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Xe",
        name: "Xenon",
        atomic_number: 54,
        atomic_mass: 131.293_f64,
        electronegativity: Some(2.6_f64),
        group: Some(18),
        period: 5,
        category: "noble gas",
        electron_configuration: "[Kr] 4d¹⁰ 5s² 5p⁶",
        isotopes: vec![
        Isotope {
            name: "Xenon-124",
            symbol: "¹²⁴Xe",
            mass_number: 124,
            neutrons: 70,
            atomic_mass: 123.905893_f64,
            half_life: Some(1.8e+22_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Tellurium-124"),
            },
            ],
            natural_abundance: 0.000952_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Xenon-126",
            symbol: "¹²⁶Xe",
            mass_number: 126,
            neutrons: 72,
            atomic_mass: 125.904274_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00089_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Xenon-128",
            symbol: "¹²⁸Xe",
            mass_number: 128,
            neutrons: 74,
            atomic_mass: 127.903531_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.019102_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Xenon-129",
            symbol: "¹²⁹Xe",
            mass_number: 129,
            neutrons: 75,
            atomic_mass: 128.904779_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.264006_f64,
            nuclear_spin: Some("1/2+"),
        },
        Isotope {
            name: "Xenon-130",
            symbol: "¹³⁰Xe",
            mass_number: 130,
            neutrons: 76,
            atomic_mass: 129.903508_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.04071_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Xenon-131",
            symbol: "¹³¹Xe",
            mass_number: 131,
            neutrons: 77,
            atomic_mass: 130.905082_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.212324_f64,
            nuclear_spin: Some("3/2+"),
        },
        Isotope {
            name: "Xenon-132",
            symbol: "¹³²Xe",
            mass_number: 132,
            neutrons: 78,
            atomic_mass: 131.904154_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.269086_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Xenon-133",
            symbol: "¹³³Xe",
            mass_number: 133,
            neutrons: 79,
            atomic_mass: 132.905911_f64,
            half_life: Some(5.2475_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Cesium-133"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Xenon-134",
            symbol: "¹³⁴Xe",
            mass_number: 134,
            neutrons: 80,
            atomic_mass: 133.905395_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.104357_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Xenon-135",
            symbol: "¹³⁵Xe",
            mass_number: 135,
            neutrons: 81,
            atomic_mass: 134.907227_f64,
            half_life: Some(9.14_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Cesium-135"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Xenon-136",
            symbol: "¹³⁶Xe",
            mass_number: 136,
            neutrons: 82,
            atomic_mass: 135.907219_f64,
            half_life: Some(2.165e+21_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double beta- (double electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Barium-136"),
            },
            ],
            natural_abundance: 0.088573_f64,
            nuclear_spin: None,
        },
        ],
    }
}
