use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Cd",
        name: "Cadmium",
        atomic_number: 48,
        atomic_mass: 112.414_f64,
        electronegativity: Some(1.69_f64),
        group: Some(12),
        period: 5,
        category: "transition metal",
        electron_configuration: "[Kr] 4d¹⁰ 5s²",
        isotopes: vec![
        Isotope {
            name: "Cadmium-106",
            symbol: "¹⁰⁶Cd",
            mass_number: 106,
            neutrons: 58,
            atomic_mass: 105.906459_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0125_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Cadmium-108",
            symbol: "¹⁰⁸Cd",
            mass_number: 108,
            neutrons: 60,
            atomic_mass: 107.904184_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0089_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Cadmium-109",
            symbol: "¹⁰⁹Cd",
            mass_number: 109,
            neutrons: 61,
            atomic_mass: 108.904982_f64,
            half_life: Some(461.4_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Silver-109"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Cadmium-110",
            symbol: "¹¹⁰Cd",
            mass_number: 110,
            neutrons: 62,
            atomic_mass: 109.903002_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1249_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Cadmium-111",
            symbol: "¹¹¹Cd",
            mass_number: 111,
            neutrons: 63,
            atomic_mass: 110.904178_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.128_f64,
            nuclear_spin: Some("1/2+"),
        },
        Isotope {
            name: "Cadmium-112",
            symbol: "¹¹²Cd",
            mass_number: 112,
            neutrons: 64,
            atomic_mass: 111.902758_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2413_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Cadmium-113",
            symbol: "¹¹³Cd",
            mass_number: 113,
            neutrons: 65,
            atomic_mass: 112.904402_f64,
            half_life: Some(8040000000000000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Indium-113"),
            },
            ],
            natural_abundance: 0.1222_f64,
            nuclear_spin: Some("1/2+"),
        },
        Isotope {
            name: "Cadmium-114",
            symbol: "¹¹⁴Cd",
            mass_number: 114,
            neutrons: 66,
            atomic_mass: 113.903359_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2873_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Cadmium-116",
            symbol: "¹¹⁶Cd",
            mass_number: 116,
            neutrons: 68,
            atomic_mass: 115.904756_f64,
            half_life: Some(2.9e+19_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Tin-116"),
            },
            ],
            natural_abundance: 0.0749_f64,
            nuclear_spin: None,
        },
        ],
    }
}
