use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Cr",
        name: "Chromium",
        atomic_number: 24,
        atomic_mass: 51.9961_f64,
        electronegativity: Some(1.66_f64),
        group: Some(6),
        period: 4,
        category: "transition metal",
        electron_configuration: "[Ar] 3d⁵ 4s¹",
        isotopes: vec![
        Isotope {
            name: "Chromium-50",
            symbol: "⁵⁰Cr",
            mass_number: 50,
            neutrons: 26,
            atomic_mass: 49.946044_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.04345_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Chromium-51",
            symbol: "⁵¹Cr",
            mass_number: 51,
            neutrons: 27,
            atomic_mass: 50.944767_f64,
            half_life: Some(27.7025_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Vanadium-51"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Chromium-52",
            symbol: "⁵²Cr",
            mass_number: 52,
            neutrons: 28,
            atomic_mass: 51.940508_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.83789_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Chromium-53",
            symbol: "⁵³Cr",
            mass_number: 53,
            neutrons: 29,
            atomic_mass: 52.940649_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.09501_f64,
            nuclear_spin: Some("3/2-"),
        },
        Isotope {
            name: "Chromium-54",
            symbol: "⁵⁴Cr",
            mass_number: 54,
            neutrons: 30,
            atomic_mass: 53.93888_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.02365_f64,
            nuclear_spin: None,
        },
        ],
    }
}
