use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Hf",
        name: "Hafnium",
        atomic_number: 72,
        atomic_mass: 178.49_f64,
        electronegativity: Some(1.3_f64),
        group: Some(4),
        period: 6,
        category: "transition metal",
        electron_configuration: "[Xe] 4f¹⁴ 5d² 6s²",
        isotopes: vec![
        Isotope {
            name: "Hafnium-174",
            symbol: "¹⁷⁴Hf",
            mass_number: 174,
            neutrons: 102,
            atomic_mass: 173.940046_f64,
            half_life: Some(2000000000000000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha",
                branching_ratio: 1.0_f64,
                daughter: Some("Ytterbium-170"),
            },
            ],
            natural_abundance: 0.0016_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Hafnium-176",
            symbol: "¹⁷⁶Hf",
            mass_number: 176,
            neutrons: 104,
            atomic_mass: 175.941409_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0526_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Hafnium-177",
            symbol: "¹⁷⁷Hf",
            mass_number: 177,
            neutrons: 105,
            atomic_mass: 176.943221_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.186_f64,
            nuclear_spin: Some("7/2-"),
        },
        Isotope {
            name: "Hafnium-178",
            symbol: "¹⁷⁸Hf",
            mass_number: 178,
            neutrons: 106,
            atomic_mass: 177.943699_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2728_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Hafnium-178m2",
            symbol: "¹⁷⁸ᵐ²Hf",
            mass_number: 178,
            neutrons: 106,
            atomic_mass: 177.943699_f64,
            half_life: Some(31.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "isomeric transition",
                branching_ratio: 1.0_f64,
                daughter: Some("Hafnium-178"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Hafnium-179",
            symbol: "¹⁷⁹Hf",
            mass_number: 179,
            neutrons: 107,
            atomic_mass: 178.945816_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1362_f64,
            nuclear_spin: Some("9/2+"),
        },
        Isotope {
            name: "Hafnium-180",
            symbol: "¹⁸⁰Hf",
            mass_number: 180,
            neutrons: 108,
            atomic_mass: 179.94655_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.3508_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Hafnium-182",
            symbol: "¹⁸²Hf",
            mass_number: 182,
            neutrons: 110,
            atomic_mass: 181.950554_f64,
            half_life: Some(8900000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Tantalum-182"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
