use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Fe",
        name: "Iron",
        atomic_number: 26,
        atomic_mass: 55.845_f64,
        electronegativity: Some(1.83_f64),
        group: Some(8),
        period: 4,
        category: "transition metal",
        electron_configuration: "[Ar] 3d⁶ 4s²",
        isotopes: vec![
        Isotope {
            name: "Iron-54",
            symbol: "⁵⁴Fe",
            mass_number: 54,
            neutrons: 28,
            atomic_mass: 53.939611_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.05845_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Iron-55",
            symbol: "⁵⁵Fe",
            mass_number: 55,
            neutrons: 29,
            atomic_mass: 54.938293_f64,
            half_life: Some(2.744_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Manganese-55"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Iron-56",
            symbol: "⁵⁶Fe",
            mass_number: 56,
            neutrons: 30,
            atomic_mass: 55.934937_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.91754_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Iron-57",
            symbol: "⁵⁷Fe",
            mass_number: 57,
            neutrons: 31,
            atomic_mass: 56.935394_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.02119_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Iron-58",
            symbol: "⁵⁸Fe",
            mass_number: 58,
            neutrons: 32,
            atomic_mass: 57.933276_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00282_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Iron-59",
            symbol: "⁵⁹Fe",
            mass_number: 59,
            neutrons: 33,
            atomic_mass: 58.934876_f64,
            half_life: Some(44.495_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Cobalt-59"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Iron-60",
            symbol: "⁶⁰Fe",
            mass_number: 60,
            neutrons: 34,
            atomic_mass: 59.934072_f64,
            half_life: Some(2600000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Cobalt-60"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
