use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Hg",
        name: "Mercury",
        atomic_number: 80,
        atomic_mass: 200.592_f64,
        electronegativity: Some(2.0_f64),
        group: Some(12),
        period: 6,
        category: "transition metal",
        electron_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
        isotopes: vec![
        Isotope {
            name: "Mercury-196",
            symbol: "¹⁹⁶Hg",
            mass_number: 196,
            neutrons: 116,
            atomic_mass: 195.965833_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0015_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Mercury-198",
            symbol: "¹⁹⁸Hg",
            mass_number: 198,
            neutrons: 118,
            atomic_mass: 197.966769_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0997_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Mercury-199",
            symbol: "¹⁹⁹Hg",
            mass_number: 199,
            neutrons: 119,
            atomic_mass: 198.96828_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1687_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Mercury-200",
            symbol: "²⁰⁰Hg",
            mass_number: 200,
            neutrons: 120,
            atomic_mass: 199.968326_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.231_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Mercury-201",
            symbol: "²⁰¹Hg",
            mass_number: 201,
            neutrons: 121,
            atomic_mass: 200.970302_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1318_f64,
            nuclear_spin: Some("3/2-"),
        },
        Isotope {
            name: "Mercury-202",
            symbol: "²⁰²Hg",
            mass_number: 202,
            neutrons: 122,
            atomic_mass: 201.970643_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2986_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Mercury-203",
            symbol: "²⁰³Hg",
            mass_number: 203,
            neutrons: 123,
            atomic_mass: 202.972873_f64,
            half_life: Some(46.594_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Thallium-203"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Mercury-204",
            symbol: "²⁰⁴Hg",
            mass_number: 204,
            neutrons: 124,
            atomic_mass: 203.973494_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0687_f64,
            nuclear_spin: None,
        },
        ],
    }
}
