use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Mo",
        name: "Molybdenum",
        atomic_number: 42,
        atomic_mass: 95.95_f64,
        electronegativity: Some(2.16_f64),
        group: Some(6),
        period: 5,
        category: "transition metal",
        electron_configuration: "[Kr] 4d⁵ 5s¹",
        isotopes: vec![
        Isotope {
            name: "Molybdenum-92",
            symbol: "⁹²Mo",
            mass_number: 92,
            neutrons: 50,
            atomic_mass: 91.906811_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1453_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Molybdenum-94",
            symbol: "⁹⁴Mo",
            mass_number: 94,
            neutrons: 52,
            atomic_mass: 93.905088_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0915_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Molybdenum-95",
            symbol: "⁹⁵Mo",
            mass_number: 95,
            neutrons: 53,
            atomic_mass: 94.905842_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1584_f64,
            nuclear_spin: Some("5/2+"),
        },
        Isotope {
            name: "Molybdenum-96",
            symbol: "⁹⁶Mo",
            mass_number: 96,
            neutrons: 54,
            atomic_mass: 95.90468_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1667_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Molybdenum-97",
            symbol: "⁹⁷Mo",
            mass_number: 97,
            neutrons: 55,
            atomic_mass: 96.906021_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.096_f64,
            nuclear_spin: Some("5/2+"),
        },
        Isotope {
            name: "Molybdenum-98",
            symbol: "⁹⁸Mo",
            mass_number: 98,
            neutrons: 56,
            atomic_mass: 97.905408_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2439_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Molybdenum-99",
            symbol: "⁹⁹Mo",
            mass_number: 99,
            neutrons: 57,
            atomic_mass: 98.907712_f64,
            half_life: Some(65.924_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Technetium-99m"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Molybdenum-100",
            symbol: "¹⁰⁰Mo",
            mass_number: 100,
            neutrons: 58,
            atomic_mass: 99.907477_f64,
            half_life: Some(8.5e+18_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Ruthenium-100"),
            },
            ],
            natural_abundance: 0.0982_f64,
            nuclear_spin: None,
        },
        ],
    }
}
