use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Ni",
        name: "Nickel",
        atomic_number: 28,
        atomic_mass: 58.6934_f64,
        electronegativity: Some(1.91_f64),
        group: Some(10),
        period: 4,
        category: "transition metal",
        electron_configuration: "[Ar] 3d⁸ 4s²",
        isotopes: vec![
        Isotope {
            name: "Nickel-56",
            symbol: "⁵⁶Ni",
            mass_number: 56,
            neutrons: 28,
            atomic_mass: 55.942132_f64,
            half_life: Some(6.075_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Cobalt-56"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Nickel-58",
            symbol: "⁵⁸Ni",
            mass_number: 58,
            neutrons: 30,
            atomic_mass: 57.935343_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.68077_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Nickel-59",
            symbol: "⁵⁹Ni",
            mass_number: 59,
            neutrons: 31,
            atomic_mass: 58.934347_f64,
            half_life: Some(76000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Cobalt-59"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Nickel-60",
            symbol: "⁶⁰Ni",
            mass_number: 60,
            neutrons: 32,
            atomic_mass: 59.930786_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.26223_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Nickel-61",
            symbol: "⁶¹Ni",
            mass_number: 61,
            neutrons: 33,
            atomic_mass: 60.931056_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0114_f64,
            nuclear_spin: Some("3/2-"),
        },
        Isotope {
            name: "Nickel-62",
            symbol: "⁶²Ni",
            mass_number: 62,
            neutrons: 34,
            atomic_mass: 61.928345_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.03634_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Nickel-63",
            symbol: "⁶³Ni",
            mass_number: 63,
            neutrons: 35,
            atomic_mass: 62.929669_f64,
            half_life: Some(101.2_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Copper-63"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Nickel-64",
            symbol: "⁶⁴Ni",
            mass_number: 64,
            neutrons: 36,
            atomic_mass: 63.927966_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00926_f64,
            nuclear_spin: None,
        },
        ],
    }
}
