use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Os",
        name: "Osmium",
        atomic_number: 76,
        atomic_mass: 190.23_f64,
        electronegativity: Some(2.2_f64),
        group: Some(8),
        period: 6,
        category: "transition metal",
        electron_configuration: "[Xe] 4f¹⁴ 5d⁶ 6s²",
        isotopes: vec![
        Isotope {
            name: "Osmium-184",
            symbol: "¹⁸⁴Os",
            mass_number: 184,
            neutrons: 108,
            atomic_mass: 183.952489_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0002_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Osmium-186",
            symbol: "¹⁸⁶Os",
            mass_number: 186,
            neutrons: 110,
            atomic_mass: 185.953838_f64,
            half_life: Some(2000000000000000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha",
                branching_ratio: 1.0_f64,
                daughter: Some("Tungsten-182"),
            },
            ],
            natural_abundance: 0.0159_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Osmium-187",
            symbol: "¹⁸⁷Os",
            mass_number: 187,
            neutrons: 111,
            atomic_mass: 186.95575_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0196_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Osmium-188",
            symbol: "¹⁸⁸Os",
            mass_number: 188,
            neutrons: 112,
            atomic_mass: 187.955838_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1324_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Osmium-189",
            symbol: "¹⁸⁹Os",
            mass_number: 189,
            neutrons: 113,
            atomic_mass: 188.958148_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1615_f64,
            nuclear_spin: Some("3/2-"),
        },
        Isotope {
            name: "Osmium-190",
            symbol: "¹⁹⁰Os",
            mass_number: 190,
            neutrons: 114,
            atomic_mass: 189.958447_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2626_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Osmium-192",
            symbol: "¹⁹²Os",
            mass_number: 192,
            neutrons: 116,
            atomic_mass: 191.961481_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.4078_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Osmium-194",
            symbol: "¹⁹⁴Os",
            mass_number: 194,
            neutrons: 118,
            atomic_mass: 193.965182_f64,
            half_life: Some(6.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Iridium-194"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
