use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Pd",
        name: "Palladium",
        atomic_number: 46,
        atomic_mass: 106.42_f64,
        electronegativity: Some(2.2_f64),
        group: Some(10),
        period: 5,
        category: "transition metal",
        electron_configuration: "[Kr] 4d¹⁰",
        isotopes: vec![
        Isotope {
            name: "Palladium-102",
            symbol: "¹⁰²Pd",
            mass_number: 102,
            neutrons: 56,
            atomic_mass: 101.905609_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0102_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Palladium-103",
            symbol: "¹⁰³Pd",
            mass_number: 103,
            neutrons: 57,
            atomic_mass: 102.906087_f64,
            half_life: Some(16.991_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Rhodium-103"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Palladium-104",
            symbol: "¹⁰⁴Pd",
            mass_number: 104,
            neutrons: 58,
            atomic_mass: 103.904036_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1114_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Palladium-105",
            symbol: "¹⁰⁵Pd",
            mass_number: 105,
            neutrons: 59,
            atomic_mass: 104.905085_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2233_f64,
            nuclear_spin: Some("5/2+"),
        },
        Isotope {
            name: "Palladium-106",
            symbol: "¹⁰⁶Pd",
            mass_number: 106,
            neutrons: 60,
            atomic_mass: 105.903486_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2733_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Palladium-107",
            symbol: "¹⁰⁷Pd",
            mass_number: 107,
            neutrons: 61,
            atomic_mass: 106.905133_f64,
            half_life: Some(6500000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Silver-107"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Palladium-108",
            symbol: "¹⁰⁸Pd",
            mass_number: 108,
            neutrons: 62,
            atomic_mass: 107.903892_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2646_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Palladium-110",
            symbol: "¹¹⁰Pd",
            mass_number: 110,
            neutrons: 64,
            atomic_mass: 109.905153_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1172_f64,
            nuclear_spin: None,
        },
        ],
    }
}
