use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Pt",
        name: "Platinum",
        atomic_number: 78,
        atomic_mass: 195.084_f64,
        electronegativity: Some(2.28_f64),
        group: Some(10),
        period: 6,
        category: "transition metal",
        electron_configuration: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
        isotopes: vec![
        Isotope {
            name: "Platinum-190",
            symbol: "¹⁹⁰Pt",
            mass_number: 190,
            neutrons: 112,
            atomic_mass: 189.959932_f64,
            half_life: Some(483000000000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha",
                branching_ratio: 1.0_f64,
                daughter: Some("Osmium-186"),
            },
            ],
            natural_abundance: 0.00012_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Platinum-192",
            symbol: "¹⁹²Pt",
            mass_number: 192,
            neutrons: 114,
            atomic_mass: 191.96104_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00782_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Platinum-194",
            symbol: "¹⁹⁴Pt",
            mass_number: 194,
            neutrons: 116,
            atomic_mass: 193.96268_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.32864_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Platinum-195",
            symbol: "¹⁹⁵Pt",
            mass_number: 195,
            neutrons: 117,
            atomic_mass: 194.964791_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.33775_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Platinum-196",
            symbol: "¹⁹⁶Pt",
            mass_number: 196,
            neutrons: 118,
            atomic_mass: 195.964952_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.25211_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Platinum-198",
            symbol: "¹⁹⁸Pt",
            mass_number: 198,
            neutrons: 120,
            atomic_mass: 197.967893_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.07356_f64,
            nuclear_spin: None,
        },
        ],
    }
}
