use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Ru",
        name: "Ruthenium",
        atomic_number: 44,
        atomic_mass: 101.07_f64,
        electronegativity: Some(2.2_f64),
        group: Some(8),
        period: 5,
        category: "transition metal",
        electron_configuration: "[Kr] 4d⁷ 5s¹",
        isotopes: vec![
        Isotope {
            name: "Ruthenium-96",
            symbol: "⁹⁶Ru",
            mass_number: 96,
            neutrons: 52,
            atomic_mass: 95.907598_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0554_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Ruthenium-98",
            symbol: "⁹⁸Ru",
            mass_number: 98,
            neutrons: 54,
            atomic_mass: 97.905287_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0187_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Ruthenium-99",
            symbol: "⁹⁹Ru",
            mass_number: 99,
            neutrons: 55,
            atomic_mass: 98.905939_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1276_f64,
            nuclear_spin: Some("5/2+"),
        },
        Isotope {
            name: "Ruthenium-100",
            symbol: "¹⁰⁰Ru",
            mass_number: 100,
            neutrons: 56,
            atomic_mass: 99.90422_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.126_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Ruthenium-101",
            symbol: "¹⁰¹Ru",
            mass_number: 101,
            neutrons: 57,
            atomic_mass: 100.905582_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1706_f64,
            nuclear_spin: Some("5/2+"),
        },
        Isotope {
            name: "Ruthenium-102",
            symbol: "¹⁰²Ru",
            mass_number: 102,
            neutrons: 58,
            atomic_mass: 101.904349_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.3155_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Ruthenium-103",
            symbol: "¹⁰³Ru",
            mass_number: 103,
            neutrons: 59,
            atomic_mass: 102.906324_f64,
            half_life: Some(39.247_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Rhodium-103"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Ruthenium-104",
            symbol: "¹⁰⁴Ru",
            mass_number: 104,
            neutrons: 60,
            atomic_mass: 103.905433_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1862_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Ruthenium-106",
            symbol: "¹⁰⁶Ru",
            mass_number: 106,
            neutrons: 62,
            atomic_mass: 105.907329_f64,
            half_life: Some(371.8_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Rhodium-106"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
