use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Ag",
        name: "Silver",
        atomic_number: 47,
        atomic_mass: 107.8682_f64,
        electronegativity: Some(1.93_f64),
        group: Some(11),
        period: 5,
        category: "transition metal",
        electron_configuration: "[Kr] 4d¹⁰ 5s¹",
        isotopes: vec![
        Isotope {
            name: "Silver-105",
            symbol: "¹⁰⁵Ag",
            mass_number: 105,
            neutrons: 58,
            atomic_mass: 104.906529_f64,
            half_life: Some(41.29_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Palladium-105"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Silver-107",
            symbol: "¹⁰⁷Ag",
            mass_number: 107,
            neutrons: 60,
            atomic_mass: 106.905097_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.51839_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Silver-108m",
            symbol: "¹⁰⁸ᵐAg",
            mass_number: 108,
            neutrons: 61,
            atomic_mass: 107.905956_f64,
            half_life: Some(418.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.912_f64,
                daughter: Some("Palladium-108"),
            },
            DecayMode {
                mode: "isomeric transition",
                branching_ratio: 0.088_f64,
                daughter: Some("Silver-108"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Silver-109",
            symbol: "¹⁰⁹Ag",
            mass_number: 109,
            neutrons: 62,
            atomic_mass: 108.904752_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.48161_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Silver-110m",
            symbol: "¹¹⁰ᵐAg",
            mass_number: 110,
            neutrons: 63,
            atomic_mass: 109.906107_f64,
            half_life: Some(249.83_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 0.987_f64,
                daughter: Some("Cadmium-110"),
            },
            DecayMode {
                mode: "isomeric transition",
                branching_ratio: 0.013_f64,
                daughter: Some("Silver-110"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Silver-111",
            symbol: "¹¹¹Ag",
            mass_number: 111,
            neutrons: 64,
            atomic_mass: 110.905291_f64,
            half_life: Some(7.45_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Cadmium-111"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
