use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Ti",
        name: "Titanium",
        atomic_number: 22,
        atomic_mass: 47.867_f64,
        electronegativity: Some(1.54_f64),
        group: Some(4),
        period: 4,
        category: "transition metal",
        electron_configuration: "[Ar] 3d² 4s²",
        isotopes: vec![
        Isotope {
            name: "Titanium-44",
            symbol: "⁴⁴Ti",
            mass_number: 44,
            neutrons: 22,
            atomic_mass: 43.95969_f64,
            half_life: Some(60.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Scandium-44"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Titanium-46",
            symbol: "⁴⁶Ti",
            mass_number: 46,
            neutrons: 24,
            atomic_mass: 45.952632_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0825_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Titanium-47",
            symbol: "⁴⁷Ti",
            mass_number: 47,
            neutrons: 25,
            atomic_mass: 46.951763_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0744_f64,
            nuclear_spin: Some("5/2-"),
        },
        Isotope {
            name: "Titanium-48",
            symbol: "⁴⁸Ti",
            mass_number: 48,
            neutrons: 26,
            atomic_mass: 47.947946_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.7372_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Titanium-49",
            symbol: "⁴⁹Ti",
            mass_number: 49,
            neutrons: 27,
            atomic_mass: 48.94787_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0541_f64,
            nuclear_spin: Some("7/2-"),
        },
        Isotope {
            name: "Titanium-50",
            symbol: "⁵⁰Ti",
            mass_number: 50,
            neutrons: 28,
            atomic_mass: 49.944792_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0518_f64,
            nuclear_spin: None,
        },
        ],
    }
}
