use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "W",
        name: "Tungsten",
        atomic_number: 74,
        atomic_mass: 183.84_f64,
        electronegativity: Some(2.36_f64),
        group: Some(6),
        period: 6,
        category: "transition metal",
        electron_configuration: "[Xe] 4f¹⁴ 5d⁴ 6s²",
        isotopes: vec![
        Isotope {
            name: "Tungsten-180",
            symbol: "¹⁸⁰W",
            mass_number: 180,
            neutrons: 106,
            atomic_mass: 179.946704_f64,
            half_life: Some(1.8e+18_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha",
                branching_ratio: 1.0_f64,
                daughter: Some("Hafnium-176"),
            },
            ],
            natural_abundance: 0.0012_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tungsten-182",
            symbol: "¹⁸²W",
            mass_number: 182,
            neutrons: 108,
            atomic_mass: 181.948204_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.265_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tungsten-183",
            symbol: "¹⁸³W",
            mass_number: 183,
            neutrons: 109,
            atomic_mass: 182.950223_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1431_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Tungsten-184",
            symbol: "¹⁸⁴W",
            mass_number: 184,
            neutrons: 110,
            atomic_mass: 183.950931_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.3064_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tungsten-186",
            symbol: "¹⁸⁶W",
            mass_number: 186,
            neutrons: 112,
            atomic_mass: 185.954364_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2843_f64,
            nuclear_spin: None,
        },
        ],
    }
}
