use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Y",
        name: "Yttrium",
        atomic_number: 39,
        atomic_mass: 88.90584_f64,
        electronegativity: Some(1.22_f64),
        group: Some(3),
        period: 5,
        category: "transition metal",
        electron_configuration: "[Kr] 4d¹ 5s²",
        isotopes: vec![
        Isotope {
            name: "Yttrium-86",
            symbol: "⁸⁶Y",
            mass_number: 86,
            neutrons: 47,
            atomic_mass: 85.914886_f64,
            half_life: Some(14.74_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+",
                branching_ratio: 1.0_f64,
                daughter: Some("Strontium-86"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Yttrium-87",
            symbol: "⁸⁷Y",
            mass_number: 87,
            neutrons: 48,
            atomic_mass: 86.910876_f64,
            half_life: Some(79.8_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture / beta+",
                branching_ratio: 1.0_f64,
                daughter: Some("Strontium-87"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Yttrium-88",
            symbol: "⁸⁸Y",
            mass_number: 88,
            neutrons: 49,
            atomic_mass: 87.909501_f64,
            half_life: Some(106.626_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ / electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Strontium-88"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Yttrium-89",
            symbol: "⁸⁹Y",
            mass_number: 89,
            neutrons: 50,
            atomic_mass: 88.905848_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 1.0_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Yttrium-90",
            symbol: "⁹⁰Y",
            mass_number: 90,
            neutrons: 51,
            atomic_mass: 89.907152_f64,
            half_life: Some(64.053_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Zirconium-90"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Yttrium-91",
            symbol: "⁹¹Y",
            mass_number: 91,
            neutrons: 52,
            atomic_mass: 90.907305_f64,
            half_life: Some(58.51_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Zirconium-91"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
