use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Zn",
        name: "Zinc",
        atomic_number: 30,
        atomic_mass: 65.38_f64,
        electronegativity: Some(1.65_f64),
        group: Some(12),
        period: 4,
        category: "transition metal",
        electron_configuration: "[Ar] 3d¹⁰ 4s²",
        isotopes: vec![
        Isotope {
            name: "Zinc-64",
            symbol: "⁶⁴Zn",
            mass_number: 64,
            neutrons: 34,
            atomic_mass: 63.929142_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.4917_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Zinc-65",
            symbol: "⁶⁵Zn",
            mass_number: 65,
            neutrons: 35,
            atomic_mass: 64.929241_f64,
            half_life: Some(243.93_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ / electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Copper-65"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Zinc-66",
            symbol: "⁶⁶Zn",
            mass_number: 66,
            neutrons: 36,
            atomic_mass: 65.926033_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2773_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Zinc-67",
            symbol: "⁶⁷Zn",
            mass_number: 67,
            neutrons: 37,
            atomic_mass: 66.927127_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0404_f64,
            nuclear_spin: Some("5/2-"),
        },
        Isotope {
            name: "Zinc-68",
            symbol: "⁶⁸Zn",
            mass_number: 68,
            neutrons: 38,
            atomic_mass: 67.924844_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1845_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Zinc-70",
            symbol: "⁷⁰Zn",
            mass_number: 70,
            neutrons: 40,
            atomic_mass: 69.925319_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0061_f64,
            nuclear_spin: None,
        },
        ],
    }
}
