use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Zr",
        name: "Zirconium",
        atomic_number: 40,
        atomic_mass: 91.224_f64,
        electronegativity: Some(1.33_f64),
        group: Some(4),
        period: 5,
        category: "transition metal",
        electron_configuration: "[Kr] 4d² 5s²",
        isotopes: vec![
        Isotope {
            name: "Zirconium-88",
            symbol: "⁸⁸Zr",
            mass_number: 88,
            neutrons: 48,
            atomic_mass: 87.910227_f64,
            half_life: Some(83.4_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Yttrium-88"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Zirconium-89",
            symbol: "⁸⁹Zr",
            mass_number: 89,
            neutrons: 49,
            atomic_mass: 88.90889_f64,
            half_life: Some(78.41_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ / electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Yttrium-89"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Zirconium-90",
            symbol: "⁹⁰Zr",
            mass_number: 90,
            neutrons: 50,
            atomic_mass: 89.904704_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.5145_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Zirconium-91",
            symbol: "⁹¹Zr",
            mass_number: 91,
            neutrons: 51,
            atomic_mass: 90.905646_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1122_f64,
            nuclear_spin: Some("5/2+"),
        },
        Isotope {
            name: "Zirconium-92",
            symbol: "⁹²Zr",
            mass_number: 92,
            neutrons: 52,
            atomic_mass: 91.905041_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1715_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Zirconium-93",
            symbol: "⁹³Zr",
            mass_number: 93,
            neutrons: 53,
            atomic_mass: 92.906476_f64,
            half_life: Some(1530000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Niobium-93"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Zirconium-94",
            symbol: "⁹⁴Zr",
            mass_number: 94,
            neutrons: 54,
            atomic_mass: 93.906315_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1738_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Zirconium-96",
            symbol: "⁹⁶Zr",
            mass_number: 96,
            neutrons: 56,
            atomic_mass: 95.908273_f64,
            half_life: Some(2.35e+19_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Molybdenum-96"),
            },
            ],
            natural_abundance: 0.028_f64,
            nuclear_spin: None,
        },
        ],
    }
}
