use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Pb",
        name: "Lead",
        atomic_number: 82,
        atomic_mass: 207.2_f64,
        electronegativity: Some(1.87_f64),
        group: Some(14),
        period: 6,
        category: "post-transition metal",
        electron_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
        isotopes: vec![
        Isotope {
            name: "Lead-204",
            symbol: "²⁰⁴Pb",
            mass_number: 204,
            neutrons: 122,
            atomic_mass: 203.973044_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.014_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Lead-205",
            symbol: "²⁰⁵Pb",
            mass_number: 205,
            neutrons: 123,
            atomic_mass: 204.974482_f64,
            half_life: Some(17300000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Thallium-205"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Lead-206",
            symbol: "²⁰⁶Pb",
            mass_number: 206,
            neutrons: 124,
            atomic_mass: 205.974465_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.241_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Lead-207",
            symbol: "²⁰⁷Pb",
            mass_number: 207,
            neutrons: 125,
            atomic_mass: 206.975897_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.221_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Lead-208",
            symbol: "²⁰⁸Pb",
            mass_number: 208,
            neutrons: 126,
            atomic_mass: 207.976652_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.524_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Lead-210",
            symbol: "²¹⁰Pb",
            mass_number: 210,
            neutrons: 128,
            atomic_mass: 209.984189_f64,
            half_life: Some(22.2_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Bismuth-210"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Lead-212",
            symbol: "²¹²Pb",
            mass_number: 212,
            neutrons: 130,
            atomic_mass: 211.991898_f64,
            half_life: Some(10.64_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Bismuth-212"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
