use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Sn",
        name: "Tin",
        atomic_number: 50,
        atomic_mass: 118.71_f64,
        electronegativity: Some(1.96_f64),
        group: Some(14),
        period: 5,
        category: "post-transition metal",
        electron_configuration: "[Kr] 4d¹⁰ 5s² 5p²",
        isotopes: vec![
        Isotope {
            name: "Tin-112",
            symbol: "¹¹²Sn",
            mass_number: 112,
            neutrons: 62,
            atomic_mass: 111.904818_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0097_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tin-114",
            symbol: "¹¹⁴Sn",
            mass_number: 114,
            neutrons: 64,
            atomic_mass: 113.902779_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0066_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tin-115",
            symbol: "¹¹⁵Sn",
            mass_number: 115,
            neutrons: 65,
            atomic_mass: 114.903342_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0034_f64,
            nuclear_spin: Some("1/2+"),
        },
        Isotope {
            name: "Tin-116",
            symbol: "¹¹⁶Sn",
            mass_number: 116,
            neutrons: 66,
            atomic_mass: 115.901741_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1454_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tin-117",
            symbol: "¹¹⁷Sn",
            mass_number: 117,
            neutrons: 67,
            atomic_mass: 116.902952_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0768_f64,
            nuclear_spin: Some("1/2+"),
        },
        Isotope {
            name: "Tin-118",
            symbol: "¹¹⁸Sn",
            mass_number: 118,
            neutrons: 68,
            atomic_mass: 117.901603_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2422_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tin-119",
            symbol: "¹¹⁹Sn",
            mass_number: 119,
            neutrons: 69,
            atomic_mass: 118.903308_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0859_f64,
            nuclear_spin: Some("1/2+"),
        },
        Isotope {
            name: "Tin-120",
            symbol: "¹²⁰Sn",
            mass_number: 120,
            neutrons: 70,
            atomic_mass: 119.902195_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.3258_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tin-122",
            symbol: "¹²²Sn",
            mass_number: 122,
            neutrons: 72,
            atomic_mass: 121.903439_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0463_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tin-124",
            symbol: "¹²⁴Sn",
            mass_number: 124,
            neutrons: 74,
            atomic_mass: 123.905274_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0579_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tin-126",
            symbol: "¹²⁶Sn",
            mass_number: 126,
            neutrons: 76,
            atomic_mass: 125.907653_f64,
            half_life: Some(230000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Antimony-126"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
