use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Ba",
        name: "Barium",
        atomic_number: 56,
        atomic_mass: 137.327_f64,
        electronegativity: Some(0.89_f64),
        group: Some(2),
        period: 6,
        category: "alkaline earth metal",
        electron_configuration: "[Xe] 6s²",
        isotopes: vec![
        Isotope {
            name: "Barium-130",
            symbol: "¹³⁰Ba",
            mass_number: 130,
            neutrons: 74,
            atomic_mass: 129.906321_f64,
            half_life: Some(1.6e+21_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Xenon-130"),
            },
            ],
            natural_abundance: 0.00106_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Barium-132",
            symbol: "¹³²Ba",
            mass_number: 132,
            neutrons: 76,
            atomic_mass: 131.905061_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00101_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Barium-133",
            symbol: "¹³³Ba",
            mass_number: 133,
            neutrons: 77,
            atomic_mass: 132.906007_f64,
            half_life: Some(10.551_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Cesium-133"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Barium-134",
            symbol: "¹³⁴Ba",
            mass_number: 134,
            neutrons: 78,
            atomic_mass: 133.904508_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.02417_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Barium-135",
            symbol: "¹³⁵Ba",
            mass_number: 135,
            neutrons: 79,
            atomic_mass: 134.905689_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.06592_f64,
            nuclear_spin: Some("3/2+"),
        },
        Isotope {
            name: "Barium-136",
            symbol: "¹³⁶Ba",
            mass_number: 136,
            neutrons: 80,
            atomic_mass: 135.904576_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.07854_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Barium-137",
            symbol: "¹³⁷Ba",
            mass_number: 137,
            neutrons: 81,
            atomic_mass: 136.905827_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.11232_f64,
            nuclear_spin: Some("3/2+"),
        },
        Isotope {
            name: "Barium-138",
            symbol: "¹³⁸Ba",
            mass_number: 138,
            neutrons: 82,
            atomic_mass: 137.905247_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.71698_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Barium-139",
            symbol: "¹³⁹Ba",
            mass_number: 139,
            neutrons: 83,
            atomic_mass: 138.908841_f64,
            half_life: Some(83.06_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Lanthanum-139"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Barium-140",
            symbol: "¹⁴⁰Ba",
            mass_number: 140,
            neutrons: 84,
            atomic_mass: 139.910606_f64,
            half_life: Some(12.752_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Lanthanum-140"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
