use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Be",
        name: "Beryllium",
        atomic_number: 4,
        atomic_mass: 9.0121831_f64,
        electronegativity: Some(1.57_f64),
        group: Some(2),
        period: 2,
        category: "alkaline earth metal",
        electron_configuration: "1s² 2s²",
        isotopes: vec![
        Isotope {
            name: "Beryllium-5",
            symbol: "⁵Be",
            mass_number: 5,
            neutrons: 1,
            atomic_mass: 5.04079_f64,
            half_life: None,
            half_life_unit: None,
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "proton emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Beryllium-6",
            symbol: "⁶Be",
            mass_number: 6,
            neutrons: 2,
            atomic_mass: 6.01973_f64,
            half_life: Some(5e-21_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "two-proton emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Beryllium-7",
            symbol: "⁷Be",
            mass_number: 7,
            neutrons: 3,
            atomic_mass: 7.016929_f64,
            half_life: Some(53.22_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Lithium-7"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Beryllium-8",
            symbol: "⁸Be",
            mass_number: 8,
            neutrons: 4,
            atomic_mass: 8.005305_f64,
            half_life: Some(8.19e-17_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha emission",
                branching_ratio: 1.0_f64,
                daughter: Some("2 × Helium-4"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Beryllium-9",
            symbol: "⁹Be",
            mass_number: 9,
            neutrons: 5,
            atomic_mass: 9.012183_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 1.0_f64,
            nuclear_spin: Some("3/2-"),
        },
        Isotope {
            name: "Beryllium-10",
            symbol: "¹⁰Be",
            mass_number: 10,
            neutrons: 6,
            atomic_mass: 10.013534_f64,
            half_life: Some(1387000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Boron-10"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Beryllium-11",
            symbol: "¹¹Be",
            mass_number: 11,
            neutrons: 7,
            atomic_mass: 11.02166_f64,
            half_life: Some(13.76_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.969_f64,
                daughter: Some("Boron-11"),
            },
            DecayMode {
                mode: "beta- alpha emission",
                branching_ratio: 0.031_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Beryllium-12",
            symbol: "¹²Be",
            mass_number: 12,
            neutrons: 8,
            atomic_mass: 12.02692_f64,
            half_life: Some(20.2_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.5_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.5_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Beryllium-13",
            symbol: "¹³Be",
            mass_number: 13,
            neutrons: 9,
            atomic_mass: 13.03569_f64,
            half_life: Some(2.7e-21_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Beryllium-14",
            symbol: "¹⁴Be",
            mass_number: 14,
            neutrons: 10,
            atomic_mass: 14.04289_f64,
            half_life: Some(4.84_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.81_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.14_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- two-neutron emission",
                branching_ratio: 0.05_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
