use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Ca",
        name: "Calcium",
        atomic_number: 20,
        atomic_mass: 40.078_f64,
        electronegativity: Some(1.0_f64),
        group: Some(2),
        period: 4,
        category: "alkaline earth metal",
        electron_configuration: "[Ar] 4s²",
        isotopes: vec![
        Isotope {
            name: "Calcium-40",
            symbol: "⁴⁰Ca",
            mass_number: 40,
            neutrons: 20,
            atomic_mass: 39.962591_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.96941_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Calcium-41",
            symbol: "⁴¹Ca",
            mass_number: 41,
            neutrons: 21,
            atomic_mass: 40.962278_f64,
            half_life: Some(99400.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Potassium-41"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Calcium-42",
            symbol: "⁴²Ca",
            mass_number: 42,
            neutrons: 22,
            atomic_mass: 41.958618_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00647_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Calcium-43",
            symbol: "⁴³Ca",
            mass_number: 43,
            neutrons: 23,
            atomic_mass: 42.958767_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00135_f64,
            nuclear_spin: Some("7/2-"),
        },
        Isotope {
            name: "Calcium-44",
            symbol: "⁴⁴Ca",
            mass_number: 44,
            neutrons: 24,
            atomic_mass: 43.955482_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.02086_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Calcium-45",
            symbol: "⁴⁵Ca",
            mass_number: 45,
            neutrons: 25,
            atomic_mass: 44.956187_f64,
            half_life: Some(162.67_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Scandium-45"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Calcium-46",
            symbol: "⁴⁶Ca",
            mass_number: 46,
            neutrons: 26,
            atomic_mass: 45.953693_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 4e-05_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Calcium-47",
            symbol: "⁴⁷Ca",
            mass_number: 47,
            neutrons: 27,
            atomic_mass: 46.954546_f64,
            half_life: Some(4.536_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Scandium-47"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Calcium-48",
            symbol: "⁴⁸Ca",
            mass_number: 48,
            neutrons: 28,
            atomic_mass: 47.952534_f64,
            half_life: Some(6.4e+19_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double beta- (double electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Titanium-48"),
            },
            ],
            natural_abundance: 0.00187_f64,
            nuclear_spin: None,
        },
        ],
    }
}
