use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Mg",
        name: "Magnesium",
        atomic_number: 12,
        atomic_mass: 24.305_f64,
        electronegativity: Some(1.31_f64),
        group: Some(2),
        period: 3,
        category: "alkaline earth metal",
        electron_configuration: "[Ne] 3s²",
        isotopes: vec![
        Isotope {
            name: "Magnesium-23",
            symbol: "²³Mg",
            mass_number: 23,
            neutrons: 11,
            atomic_mass: 22.99412_f64,
            half_life: Some(11.317_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Sodium-23"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Magnesium-24",
            symbol: "²⁴Mg",
            mass_number: 24,
            neutrons: 12,
            atomic_mass: 23.985042_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.7899_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Magnesium-25",
            symbol: "²⁵Mg",
            mass_number: 25,
            neutrons: 13,
            atomic_mass: 24.985837_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1_f64,
            nuclear_spin: Some("5/2+"),
        },
        Isotope {
            name: "Magnesium-26",
            symbol: "²⁶Mg",
            mass_number: 26,
            neutrons: 14,
            atomic_mass: 25.982593_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1101_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Magnesium-27",
            symbol: "²⁷Mg",
            mass_number: 27,
            neutrons: 15,
            atomic_mass: 26.984341_f64,
            half_life: Some(9.458_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Aluminum-27"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Magnesium-28",
            symbol: "²⁸Mg",
            mass_number: 28,
            neutrons: 16,
            atomic_mass: 27.983877_f64,
            half_life: Some(20.915_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Aluminum-28"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
