use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Sr",
        name: "Strontium",
        atomic_number: 38,
        atomic_mass: 87.62_f64,
        electronegativity: Some(0.95_f64),
        group: Some(2),
        period: 5,
        category: "alkaline earth metal",
        electron_configuration: "[Kr] 5s²",
        isotopes: vec![
        Isotope {
            name: "Strontium-82",
            symbol: "⁸²Sr",
            mass_number: 82,
            neutrons: 44,
            atomic_mass: 81.918402_f64,
            half_life: Some(25.36_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Rubidium-82"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Strontium-84",
            symbol: "⁸⁴Sr",
            mass_number: 84,
            neutrons: 46,
            atomic_mass: 83.913425_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0056_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Strontium-85",
            symbol: "⁸⁵Sr",
            mass_number: 85,
            neutrons: 47,
            atomic_mass: 84.912933_f64,
            half_life: Some(64.849_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Rubidium-85"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Strontium-86",
            symbol: "⁸⁶Sr",
            mass_number: 86,
            neutrons: 48,
            atomic_mass: 85.909261_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0986_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Strontium-87",
            symbol: "⁸⁷Sr",
            mass_number: 87,
            neutrons: 49,
            atomic_mass: 86.908878_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.07_f64,
            nuclear_spin: Some("9/2+"),
        },
        Isotope {
            name: "Strontium-88",
            symbol: "⁸⁸Sr",
            mass_number: 88,
            neutrons: 50,
            atomic_mass: 87.905612_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.8258_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Strontium-89",
            symbol: "⁸⁹Sr",
            mass_number: 89,
            neutrons: 51,
            atomic_mass: 88.907453_f64,
            half_life: Some(50.57_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Yttrium-89"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Strontium-90",
            symbol: "⁹⁰Sr",
            mass_number: 90,
            neutrons: 52,
            atomic_mass: 89.907738_f64,
            half_life: Some(28.79_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Yttrium-90"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
