use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Li",
        name: "Lithium",
        atomic_number: 3,
        atomic_mass: 6.941_f64,
        electronegativity: Some(0.98_f64),
        group: Some(1),
        period: 2,
        category: "alkali metal",
        electron_configuration: "1s² 2s¹",
        isotopes: vec![
        Isotope {
            name: "Lithium-3",
            symbol: "³Li",
            mass_number: 3,
            neutrons: 0,
            atomic_mass: 3.03078_f64,
            half_life: None,
            half_life_unit: None,
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "proton emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Lithium-4",
            symbol: "⁴Li",
            mass_number: 4,
            neutrons: 1,
            atomic_mass: 4.02719_f64,
            half_life: Some(9.1e-23_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "proton emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Lithium-5",
            symbol: "⁵Li",
            mass_number: 5,
            neutrons: 2,
            atomic_mass: 5.01254_f64,
            half_life: Some(3.7e-22_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "proton emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Lithium-6",
            symbol: "⁶Li",
            mass_number: 6,
            neutrons: 3,
            atomic_mass: 6.015123_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0759_f64,
            nuclear_spin: Some("1+"),
        },
        Isotope {
            name: "Lithium-7",
            symbol: "⁷Li",
            mass_number: 7,
            neutrons: 4,
            atomic_mass: 7.016005_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.9241_f64,
            nuclear_spin: Some("3/2-"),
        },
        Isotope {
            name: "Lithium-8",
            symbol: "⁸Li",
            mass_number: 8,
            neutrons: 5,
            atomic_mass: 8.02249_f64,
            half_life: Some(839.4_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Beryllium-8"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Lithium-9",
            symbol: "⁹Li",
            mass_number: 9,
            neutrons: 6,
            atomic_mass: 9.02679_f64,
            half_life: Some(178.3_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.508_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.492_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Lithium-10",
            symbol: "¹⁰Li",
            mass_number: 10,
            neutrons: 7,
            atomic_mass: 10.03548_f64,
            half_life: Some(2e-21_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Lithium-11",
            symbol: "¹¹Li",
            mass_number: 11,
            neutrons: 8,
            atomic_mass: 11.0438_f64,
            half_life: Some(8.75_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.514_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.448_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- two-neutron emission",
                branching_ratio: 0.038_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Lithium-12",
            symbol: "¹²Li",
            mass_number: 12,
            neutrons: 9,
            atomic_mass: 12.05378_f64,
            half_life: Some(1e-20_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
