use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "K",
        name: "Potassium",
        atomic_number: 19,
        atomic_mass: 39.0983_f64,
        electronegativity: Some(0.82_f64),
        group: Some(1),
        period: 4,
        category: "alkali metal",
        electron_configuration: "[Ar] 4s¹",
        isotopes: vec![
        Isotope {
            name: "Potassium-38",
            symbol: "³⁸K",
            mass_number: 38,
            neutrons: 19,
            atomic_mass: 37.96908_f64,
            half_life: Some(7.636_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Argon-38"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Potassium-39",
            symbol: "³⁹K",
            mass_number: 39,
            neutrons: 20,
            atomic_mass: 38.963707_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.932581_f64,
            nuclear_spin: Some("3/2+"),
        },
        Isotope {
            name: "Potassium-40",
            symbol: "⁴⁰K",
            mass_number: 40,
            neutrons: 21,
            atomic_mass: 39.963999_f64,
            half_life: Some(1248000000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.8928_f64,
                daughter: Some("Calcium-40"),
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.1072_f64,
                daughter: Some("Argon-40"),
            },
            ],
            natural_abundance: 0.000117_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Potassium-41",
            symbol: "⁴¹K",
            mass_number: 41,
            neutrons: 22,
            atomic_mass: 40.961826_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.067302_f64,
            nuclear_spin: Some("3/2+"),
        },
        Isotope {
            name: "Potassium-42",
            symbol: "⁴²K",
            mass_number: 42,
            neutrons: 23,
            atomic_mass: 41.962403_f64,
            half_life: Some(12.36_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Calcium-42"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Potassium-43",
            symbol: "⁴³K",
            mass_number: 43,
            neutrons: 24,
            atomic_mass: 42.96072_f64,
            half_life: Some(22.3_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Calcium-43"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
