use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Rb",
        name: "Rubidium",
        atomic_number: 37,
        atomic_mass: 85.4678_f64,
        electronegativity: Some(0.82_f64),
        group: Some(1),
        period: 5,
        category: "alkali metal",
        electron_configuration: "[Kr] 5s¹",
        isotopes: vec![
        Isotope {
            name: "Rubidium-82",
            symbol: "⁸²Rb",
            mass_number: 82,
            neutrons: 45,
            atomic_mass: 81.918209_f64,
            half_life: Some(1.2575_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.955_f64,
                daughter: Some("Krypton-82"),
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.045_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Rubidium-83",
            symbol: "⁸³Rb",
            mass_number: 83,
            neutrons: 46,
            atomic_mass: 82.91511_f64,
            half_life: Some(86.2_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Krypton-83"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Rubidium-84",
            symbol: "⁸⁴Rb",
            mass_number: 84,
            neutrons: 47,
            atomic_mass: 83.914385_f64,
            half_life: Some(32.82_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.038_f64,
                daughter: None,
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.662_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.3_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Rubidium-85",
            symbol: "⁸⁵Rb",
            mass_number: 85,
            neutrons: 48,
            atomic_mass: 84.91179_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.7217_f64,
            nuclear_spin: Some("5/2-"),
        },
        Isotope {
            name: "Rubidium-86",
            symbol: "⁸⁶Rb",
            mass_number: 86,
            neutrons: 49,
            atomic_mass: 85.911167_f64,
            half_life: Some(18.642_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.995_f64,
                daughter: Some("Strontium-86"),
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.005_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Rubidium-87",
            symbol: "⁸⁷Rb",
            mass_number: 87,
            neutrons: 50,
            atomic_mass: 86.909181_f64,
            half_life: Some(49230000000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Strontium-87"),
            },
            ],
            natural_abundance: 0.2783_f64,
            nuclear_spin: None,
        },
        ],
    }
}
