use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Na",
        name: "Sodium",
        atomic_number: 11,
        atomic_mass: 22.98976928_f64,
        electronegativity: Some(0.93_f64),
        group: Some(1),
        period: 3,
        category: "alkali metal",
        electron_configuration: "[Ne] 3s¹",
        isotopes: vec![
        Isotope {
            name: "Sodium-20",
            symbol: "²⁰Na",
            mass_number: 20,
            neutrons: 9,
            atomic_mass: 20.00735_f64,
            half_life: Some(447.9_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.8_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta+ alpha emission",
                branching_ratio: 0.2_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Sodium-21",
            symbol: "²¹Na",
            mass_number: 21,
            neutrons: 10,
            atomic_mass: 20.99765_f64,
            half_life: Some(22.49_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Neon-21"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Sodium-22",
            symbol: "²²Na",
            mass_number: 22,
            neutrons: 11,
            atomic_mass: 21.994437_f64,
            half_life: Some(2.6018_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.899_f64,
                daughter: Some("Neon-22"),
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.101_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Sodium-23",
            symbol: "²³Na",
            mass_number: 23,
            neutrons: 12,
            atomic_mass: 22.989769_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 1.0_f64,
            nuclear_spin: Some("3/2+"),
        },
        Isotope {
            name: "Sodium-24",
            symbol: "²⁴Na",
            mass_number: 24,
            neutrons: 13,
            atomic_mass: 23.990963_f64,
            half_life: Some(14.997_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Magnesium-24"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Sodium-25",
            symbol: "²⁵Na",
            mass_number: 25,
            neutrons: 14,
            atomic_mass: 24.98995_f64,
            half_life: Some(59.1_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Magnesium-25"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Sodium-26",
            symbol: "²⁶Na",
            mass_number: 26,
            neutrons: 15,
            atomic_mass: 25.99263_f64,
            half_life: Some(1.077_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
