use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Sb",
        name: "Antimony",
        atomic_number: 51,
        atomic_mass: 121.76_f64,
        electronegativity: Some(2.05_f64),
        group: Some(15),
        period: 5,
        category: "metalloid",
        electron_configuration: "[Kr] 4d¹⁰ 5s² 5p³",
        isotopes: vec![
        Isotope {
            name: "Antimony-119",
            symbol: "¹¹⁹Sb",
            mass_number: 119,
            neutrons: 68,
            atomic_mass: 118.903942_f64,
            half_life: Some(38.19_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Tin-119"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Antimony-120",
            symbol: "¹²⁰Sb",
            mass_number: 120,
            neutrons: 69,
            atomic_mass: 119.905072_f64,
            half_life: Some(15.89_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Antimony-121",
            symbol: "¹²¹Sb",
            mass_number: 121,
            neutrons: 70,
            atomic_mass: 120.903816_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.5721_f64,
            nuclear_spin: Some("5/2+"),
        },
        Isotope {
            name: "Antimony-122",
            symbol: "¹²²Sb",
            mass_number: 122,
            neutrons: 71,
            atomic_mass: 121.905174_f64,
            half_life: Some(2.7238_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.974_f64,
                daughter: Some("Tellurium-122"),
            },
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.026_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Antimony-123",
            symbol: "¹²³Sb",
            mass_number: 123,
            neutrons: 72,
            atomic_mass: 122.904214_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.4279_f64,
            nuclear_spin: Some("7/2+"),
        },
        Isotope {
            name: "Antimony-124",
            symbol: "¹²⁴Sb",
            mass_number: 124,
            neutrons: 73,
            atomic_mass: 123.905936_f64,
            half_life: Some(60.2_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Tellurium-124"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Antimony-125",
            symbol: "¹²⁵Sb",
            mass_number: 125,
            neutrons: 74,
            atomic_mass: 124.905254_f64,
            half_life: Some(2.75856_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Tellurium-125"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
