use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "As",
        name: "Arsenic",
        atomic_number: 33,
        atomic_mass: 74.921595_f64,
        electronegativity: Some(2.18_f64),
        group: Some(15),
        period: 4,
        category: "metalloid",
        electron_configuration: "[Ar] 3d¹⁰ 4s² 4p³",
        isotopes: vec![
        Isotope {
            name: "Arsenic-71",
            symbol: "⁷¹As",
            mass_number: 71,
            neutrons: 38,
            atomic_mass: 70.92711_f64,
            half_life: Some(65.3_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.68_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.32_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Arsenic-72",
            symbol: "⁷²As",
            mass_number: 72,
            neutrons: 39,
            atomic_mass: 71.92675_f64,
            half_life: Some(26.0_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.88_f64,
                daughter: None,
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.12_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Arsenic-73",
            symbol: "⁷³As",
            mass_number: 73,
            neutrons: 40,
            atomic_mass: 72.923825_f64,
            half_life: Some(80.3_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Germanium-73"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Arsenic-74",
            symbol: "⁷⁴As",
            mass_number: 74,
            neutrons: 41,
            atomic_mass: 73.923929_f64,
            half_life: Some(17.77_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 0.34_f64,
                daughter: None,
            },
            DecayMode {
                mode: "electron capture",
                branching_ratio: 0.34_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.32_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Arsenic-75",
            symbol: "⁷⁵As",
            mass_number: 75,
            neutrons: 42,
            atomic_mass: 74.921595_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 1.0_f64,
            nuclear_spin: Some("3/2-"),
        },
        Isotope {
            name: "Arsenic-76",
            symbol: "⁷⁶As",
            mass_number: 76,
            neutrons: 43,
            atomic_mass: 75.922394_f64,
            half_life: Some(26.24_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Selenium-76"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Arsenic-77",
            symbol: "⁷⁷As",
            mass_number: 77,
            neutrons: 44,
            atomic_mass: 76.920647_f64,
            half_life: Some(38.83_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Selenium-77"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
