use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "B",
        name: "Boron",
        atomic_number: 5,
        atomic_mass: 10.81_f64,
        electronegativity: Some(2.04_f64),
        group: Some(13),
        period: 2,
        category: "metalloid",
        electron_configuration: "1s² 2s² 2p¹",
        isotopes: vec![
        Isotope {
            name: "Boron-7",
            symbol: "⁷B",
            mass_number: 7,
            neutrons: 2,
            atomic_mass: 7.02992_f64,
            half_life: Some(3.5e-22_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "proton emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Boron-8",
            symbol: "⁸B",
            mass_number: 8,
            neutrons: 3,
            atomic_mass: 8.02461_f64,
            half_life: Some(770.0_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta+ (positron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Beryllium-8"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Boron-9",
            symbol: "⁹B",
            mass_number: 9,
            neutrons: 4,
            atomic_mass: 9.01333_f64,
            half_life: Some(8e-19_f64),
            half_life_unit: Some("seconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "proton emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Boron-10",
            symbol: "¹⁰B",
            mass_number: 10,
            neutrons: 5,
            atomic_mass: 10.012937_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.199_f64,
            nuclear_spin: Some("3+"),
        },
        Isotope {
            name: "Boron-11",
            symbol: "¹¹B",
            mass_number: 11,
            neutrons: 6,
            atomic_mass: 11.009305_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.801_f64,
            nuclear_spin: Some("3/2-"),
        },
        Isotope {
            name: "Boron-12",
            symbol: "¹²B",
            mass_number: 12,
            neutrons: 7,
            atomic_mass: 12.01435_f64,
            half_life: Some(20.2_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.9714_f64,
                daughter: Some("Carbon-12"),
            },
            DecayMode {
                mode: "beta- alpha emission",
                branching_ratio: 0.0286_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Boron-13",
            symbol: "¹³B",
            mass_number: 13,
            neutrons: 8,
            atomic_mass: 13.01778_f64,
            half_life: Some(17.33_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.993_f64,
                daughter: Some("Carbon-13"),
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.007_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Boron-14",
            symbol: "¹⁴B",
            mass_number: 14,
            neutrons: 9,
            atomic_mass: 14.0254_f64,
            half_life: Some(12.5_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.937_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.063_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Boron-15",
            symbol: "¹⁵B",
            mass_number: 15,
            neutrons: 10,
            atomic_mass: 15.0311_f64,
            half_life: Some(9.87_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.93_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.07_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Boron-17",
            symbol: "¹⁷B",
            mass_number: 17,
            neutrons: 12,
            atomic_mass: 17.04699_f64,
            half_life: Some(5.08_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 0.63_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.37_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Boron-19",
            symbol: "¹⁹B",
            mass_number: 19,
            neutrons: 14,
            atomic_mass: 19.06373_f64,
            half_life: Some(2.92_f64),
            half_life_unit: Some("milliseconds"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- neutron emission",
                branching_ratio: 1.0_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
