use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Ge",
        name: "Germanium",
        atomic_number: 32,
        atomic_mass: 72.63_f64,
        electronegativity: Some(2.01_f64),
        group: Some(14),
        period: 4,
        category: "metalloid",
        electron_configuration: "[Ar] 3d¹⁰ 4s² 4p²",
        isotopes: vec![
        Isotope {
            name: "Germanium-68",
            symbol: "⁶⁸Ge",
            mass_number: 68,
            neutrons: 36,
            atomic_mass: 67.92809_f64,
            half_life: Some(270.95_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Gallium-68"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Germanium-70",
            symbol: "⁷⁰Ge",
            mass_number: 70,
            neutrons: 38,
            atomic_mass: 69.924248_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2038_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Germanium-71",
            symbol: "⁷¹Ge",
            mass_number: 71,
            neutrons: 39,
            atomic_mass: 70.924951_f64,
            half_life: Some(11.43_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Gallium-71"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Germanium-72",
            symbol: "⁷²Ge",
            mass_number: 72,
            neutrons: 40,
            atomic_mass: 71.922076_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2731_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Germanium-73",
            symbol: "⁷³Ge",
            mass_number: 73,
            neutrons: 41,
            atomic_mass: 72.923459_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0776_f64,
            nuclear_spin: Some("9/2+"),
        },
        Isotope {
            name: "Germanium-74",
            symbol: "⁷⁴Ge",
            mass_number: 74,
            neutrons: 42,
            atomic_mass: 73.921178_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.3672_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Germanium-76",
            symbol: "⁷⁶Ge",
            mass_number: 76,
            neutrons: 44,
            atomic_mass: 75.921403_f64,
            half_life: Some(1.926e+21_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double beta- (double electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Selenium-76"),
            },
            ],
            natural_abundance: 0.0783_f64,
            nuclear_spin: None,
        },
        ],
    }
}
