use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Si",
        name: "Silicon",
        atomic_number: 14,
        atomic_mass: 28.085_f64,
        electronegativity: Some(1.9_f64),
        group: Some(14),
        period: 3,
        category: "metalloid",
        electron_configuration: "[Ne] 3s² 3p²",
        isotopes: vec![
        Isotope {
            name: "Silicon-28",
            symbol: "²⁸Si",
            mass_number: 28,
            neutrons: 14,
            atomic_mass: 27.976927_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.92223_f64,
            nuclear_spin: Some("0+"),
        },
        Isotope {
            name: "Silicon-29",
            symbol: "²⁹Si",
            mass_number: 29,
            neutrons: 15,
            atomic_mass: 28.976495_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.04685_f64,
            nuclear_spin: Some("1/2+"),
        },
        Isotope {
            name: "Silicon-30",
            symbol: "³⁰Si",
            mass_number: 30,
            neutrons: 16,
            atomic_mass: 29.97377_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.03092_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Silicon-31",
            symbol: "³¹Si",
            mass_number: 31,
            neutrons: 17,
            atomic_mass: 30.975363_f64,
            half_life: Some(157.36_f64),
            half_life_unit: Some("minutes"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Phosphorus-31"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Silicon-32",
            symbol: "³²Si",
            mass_number: 32,
            neutrons: 18,
            atomic_mass: 31.974148_f64,
            half_life: Some(153.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Phosphorus-32"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
