use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Te",
        name: "Tellurium",
        atomic_number: 52,
        atomic_mass: 127.6_f64,
        electronegativity: Some(2.1_f64),
        group: Some(16),
        period: 5,
        category: "metalloid",
        electron_configuration: "[Kr] 4d¹⁰ 5s² 5p⁴",
        isotopes: vec![
        Isotope {
            name: "Tellurium-120",
            symbol: "¹²⁰Te",
            mass_number: 120,
            neutrons: 68,
            atomic_mass: 119.90402_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0009_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tellurium-122",
            symbol: "¹²²Te",
            mass_number: 122,
            neutrons: 70,
            atomic_mass: 121.903044_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0255_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tellurium-123",
            symbol: "¹²³Te",
            mass_number: 123,
            neutrons: 71,
            atomic_mass: 122.90427_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0089_f64,
            nuclear_spin: Some("1/2+"),
        },
        Isotope {
            name: "Tellurium-124",
            symbol: "¹²⁴Te",
            mass_number: 124,
            neutrons: 72,
            atomic_mass: 123.902818_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0474_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tellurium-125",
            symbol: "¹²⁵Te",
            mass_number: 125,
            neutrons: 73,
            atomic_mass: 124.904431_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0707_f64,
            nuclear_spin: Some("1/2+"),
        },
        Isotope {
            name: "Tellurium-126",
            symbol: "¹²⁶Te",
            mass_number: 126,
            neutrons: 74,
            atomic_mass: 125.903312_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1884_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tellurium-128",
            symbol: "¹²⁸Te",
            mass_number: 128,
            neutrons: 76,
            atomic_mass: 127.904463_f64,
            half_life: Some(2.2e+24_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double beta- (double electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Xenon-128"),
            },
            ],
            natural_abundance: 0.3174_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tellurium-129m",
            symbol: "¹²⁹ᵐTe",
            mass_number: 129,
            neutrons: 77,
            atomic_mass: 128.906598_f64,
            half_life: Some(33.6_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "isomeric transition",
                branching_ratio: 0.63_f64,
                daughter: None,
            },
            DecayMode {
                mode: "beta- (electron emission)",
                branching_ratio: 0.37_f64,
                daughter: None,
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Tellurium-130",
            symbol: "¹³⁰Te",
            mass_number: 130,
            neutrons: 78,
            atomic_mass: 129.906224_f64,
            half_life: Some(7.9e+20_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double beta- (double electron emission)",
                branching_ratio: 1.0_f64,
                daughter: Some("Xenon-130"),
            },
            ],
            natural_abundance: 0.3408_f64,
            nuclear_spin: None,
        },
        ],
    }
}
