use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Ce",
        name: "Cerium",
        atomic_number: 58,
        atomic_mass: 140.116_f64,
        electronegativity: Some(1.12_f64),
        group: None,
        period: 6,
        category: "lanthanide",
        electron_configuration: "[Xe] 4f¹ 5d¹ 6s²",
        isotopes: vec![
        Isotope {
            name: "Cerium-136",
            symbol: "¹³⁶Ce",
            mass_number: 136,
            neutrons: 78,
            atomic_mass: 135.907172_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00185_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Cerium-138",
            symbol: "¹³⁸Ce",
            mass_number: 138,
            neutrons: 80,
            atomic_mass: 137.905991_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00251_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Cerium-140",
            symbol: "¹⁴⁰Ce",
            mass_number: 140,
            neutrons: 82,
            atomic_mass: 139.905439_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.8845_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Cerium-141",
            symbol: "¹⁴¹Ce",
            mass_number: 141,
            neutrons: 83,
            atomic_mass: 140.908276_f64,
            half_life: Some(32.508_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Praseodymium-141"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Cerium-142",
            symbol: "¹⁴²Ce",
            mass_number: 142,
            neutrons: 84,
            atomic_mass: 141.909244_f64,
            half_life: Some(5e+16_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha",
                branching_ratio: 1.0_f64,
                daughter: Some("Barium-138"),
            },
            ],
            natural_abundance: 0.11114_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Cerium-144",
            symbol: "¹⁴⁴Ce",
            mass_number: 144,
            neutrons: 86,
            atomic_mass: 143.913647_f64,
            half_life: Some(284.91_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Praseodymium-144"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        ],
    }
}
