use super::super::{Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Dy",
        name: "Dysprosium",
        atomic_number: 66,
        atomic_mass: 162.5_f64,
        electronegativity: Some(1.22_f64),
        group: None,
        period: 6,
        category: "lanthanide",
        electron_configuration: "[Xe] 4f¹⁰ 6s²",
        isotopes: vec![
        Isotope {
            name: "Dysprosium-156",
            symbol: "¹⁵⁶Dy",
            mass_number: 156,
            neutrons: 90,
            atomic_mass: 155.924283_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00056_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Dysprosium-158",
            symbol: "¹⁵⁸Dy",
            mass_number: 158,
            neutrons: 92,
            atomic_mass: 157.924409_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00095_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Dysprosium-160",
            symbol: "¹⁶⁰Dy",
            mass_number: 160,
            neutrons: 94,
            atomic_mass: 159.925198_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.02329_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Dysprosium-161",
            symbol: "¹⁶¹Dy",
            mass_number: 161,
            neutrons: 95,
            atomic_mass: 160.926933_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.18889_f64,
            nuclear_spin: Some("5/2+"),
        },
        Isotope {
            name: "Dysprosium-162",
            symbol: "¹⁶²Dy",
            mass_number: 162,
            neutrons: 96,
            atomic_mass: 161.926798_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.25475_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Dysprosium-163",
            symbol: "¹⁶³Dy",
            mass_number: 163,
            neutrons: 97,
            atomic_mass: 162.928731_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.24896_f64,
            nuclear_spin: Some("5/2-"),
        },
        Isotope {
            name: "Dysprosium-164",
            symbol: "¹⁶⁴Dy",
            mass_number: 164,
            neutrons: 98,
            atomic_mass: 163.929175_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2826_f64,
            nuclear_spin: None,
        },
        ],
    }
}
