use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Er",
        name: "Erbium",
        atomic_number: 68,
        atomic_mass: 167.259_f64,
        electronegativity: Some(1.24_f64),
        group: None,
        period: 6,
        category: "lanthanide",
        electron_configuration: "[Xe] 4f¹² 6s²",
        isotopes: vec![
        Isotope {
            name: "Erbium-162",
            symbol: "¹⁶²Er",
            mass_number: 162,
            neutrons: 94,
            atomic_mass: 161.928778_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00139_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Erbium-164",
            symbol: "¹⁶⁴Er",
            mass_number: 164,
            neutrons: 96,
            atomic_mass: 163.9292_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.01601_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Erbium-166",
            symbol: "¹⁶⁶Er",
            mass_number: 166,
            neutrons: 98,
            atomic_mass: 165.930293_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.33503_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Erbium-167",
            symbol: "¹⁶⁷Er",
            mass_number: 167,
            neutrons: 99,
            atomic_mass: 166.932048_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.22869_f64,
            nuclear_spin: Some("7/2+"),
        },
        Isotope {
            name: "Erbium-168",
            symbol: "¹⁶⁸Er",
            mass_number: 168,
            neutrons: 100,
            atomic_mass: 167.93237_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.26978_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Erbium-169",
            symbol: "¹⁶⁹Er",
            mass_number: 169,
            neutrons: 101,
            atomic_mass: 168.93459_f64,
            half_life: Some(9.392_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Thulium-169"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Erbium-170",
            symbol: "¹⁷⁰Er",
            mass_number: 170,
            neutrons: 102,
            atomic_mass: 169.935464_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1491_f64,
            nuclear_spin: None,
        },
        ],
    }
}
