use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Gd",
        name: "Gadolinium",
        atomic_number: 64,
        atomic_mass: 157.25_f64,
        electronegativity: Some(1.2_f64),
        group: None,
        period: 6,
        category: "lanthanide",
        electron_configuration: "[Xe] 4f⁷ 5d¹ 6s²",
        isotopes: vec![
        Isotope {
            name: "Gadolinium-152",
            symbol: "¹⁵²Gd",
            mass_number: 152,
            neutrons: 88,
            atomic_mass: 151.919791_f64,
            half_life: Some(108000000000000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha",
                branching_ratio: 1.0_f64,
                daughter: Some("Samarium-148"),
            },
            ],
            natural_abundance: 0.002_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Gadolinium-154",
            symbol: "¹⁵⁴Gd",
            mass_number: 154,
            neutrons: 90,
            atomic_mass: 153.920866_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0218_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Gadolinium-155",
            symbol: "¹⁵⁵Gd",
            mass_number: 155,
            neutrons: 91,
            atomic_mass: 154.922622_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.148_f64,
            nuclear_spin: Some("3/2-"),
        },
        Isotope {
            name: "Gadolinium-156",
            symbol: "¹⁵⁶Gd",
            mass_number: 156,
            neutrons: 92,
            atomic_mass: 155.922123_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2047_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Gadolinium-157",
            symbol: "¹⁵⁷Gd",
            mass_number: 157,
            neutrons: 93,
            atomic_mass: 156.92396_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1565_f64,
            nuclear_spin: Some("3/2-"),
        },
        Isotope {
            name: "Gadolinium-158",
            symbol: "¹⁵⁸Gd",
            mass_number: 158,
            neutrons: 94,
            atomic_mass: 157.924104_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2484_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Gadolinium-160",
            symbol: "¹⁶⁰Gd",
            mass_number: 160,
            neutrons: 96,
            atomic_mass: 159.927054_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2186_f64,
            nuclear_spin: None,
        },
        ],
    }
}
