use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Nd",
        name: "Neodymium",
        atomic_number: 60,
        atomic_mass: 144.242_f64,
        electronegativity: Some(1.14_f64),
        group: None,
        period: 6,
        category: "lanthanide",
        electron_configuration: "[Xe] 4f⁴ 6s²",
        isotopes: vec![
        Isotope {
            name: "Neodymium-142",
            symbol: "¹⁴²Nd",
            mass_number: 142,
            neutrons: 82,
            atomic_mass: 141.907723_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.27152_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Neodymium-143",
            symbol: "¹⁴³Nd",
            mass_number: 143,
            neutrons: 83,
            atomic_mass: 142.909814_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.12174_f64,
            nuclear_spin: Some("7/2-"),
        },
        Isotope {
            name: "Neodymium-144",
            symbol: "¹⁴⁴Nd",
            mass_number: 144,
            neutrons: 84,
            atomic_mass: 143.910087_f64,
            half_life: Some(2290000000000000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha",
                branching_ratio: 1.0_f64,
                daughter: Some("Cerium-140"),
            },
            ],
            natural_abundance: 0.23798_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Neodymium-145",
            symbol: "¹⁴⁵Nd",
            mass_number: 145,
            neutrons: 85,
            atomic_mass: 144.912574_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.08293_f64,
            nuclear_spin: Some("7/2-"),
        },
        Isotope {
            name: "Neodymium-146",
            symbol: "¹⁴⁶Nd",
            mass_number: 146,
            neutrons: 86,
            atomic_mass: 145.913117_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.17189_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Neodymium-148",
            symbol: "¹⁴⁸Nd",
            mass_number: 148,
            neutrons: 88,
            atomic_mass: 147.916893_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.05756_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Neodymium-150",
            symbol: "¹⁵⁰Nd",
            mass_number: 150,
            neutrons: 90,
            atomic_mass: 149.920891_f64,
            half_life: Some(6.7e+18_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "double beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Samarium-150"),
            },
            ],
            natural_abundance: 0.05638_f64,
            nuclear_spin: None,
        },
        ],
    }
}
