use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Sm",
        name: "Samarium",
        atomic_number: 62,
        atomic_mass: 150.36_f64,
        electronegativity: Some(1.17_f64),
        group: None,
        period: 6,
        category: "lanthanide",
        electron_configuration: "[Xe] 4f⁶ 6s²",
        isotopes: vec![
        Isotope {
            name: "Samarium-144",
            symbol: "¹⁴⁴Sm",
            mass_number: 144,
            neutrons: 82,
            atomic_mass: 143.911999_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0307_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Samarium-147",
            symbol: "¹⁴⁷Sm",
            mass_number: 147,
            neutrons: 85,
            atomic_mass: 146.914898_f64,
            half_life: Some(106000000000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha",
                branching_ratio: 1.0_f64,
                daughter: Some("Neodymium-143"),
            },
            ],
            natural_abundance: 0.1499_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Samarium-148",
            symbol: "¹⁴⁸Sm",
            mass_number: 148,
            neutrons: 86,
            atomic_mass: 147.914823_f64,
            half_life: Some(7000000000000000.0_f64),
            half_life_unit: Some("years"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "alpha",
                branching_ratio: 1.0_f64,
                daughter: Some("Neodymium-144"),
            },
            ],
            natural_abundance: 0.1124_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Samarium-149",
            symbol: "¹⁴⁹Sm",
            mass_number: 149,
            neutrons: 87,
            atomic_mass: 148.917185_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1382_f64,
            nuclear_spin: Some("7/2-"),
        },
        Isotope {
            name: "Samarium-150",
            symbol: "¹⁵⁰Sm",
            mass_number: 150,
            neutrons: 88,
            atomic_mass: 149.917276_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.0738_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Samarium-152",
            symbol: "¹⁵²Sm",
            mass_number: 152,
            neutrons: 90,
            atomic_mass: 151.919732_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2675_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Samarium-153",
            symbol: "¹⁵³Sm",
            mass_number: 153,
            neutrons: 91,
            atomic_mass: 152.922097_f64,
            half_life: Some(46.284_f64),
            half_life_unit: Some("hours"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "beta-",
                branching_ratio: 1.0_f64,
                daughter: Some("Europium-153"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Samarium-154",
            symbol: "¹⁵⁴Sm",
            mass_number: 154,
            neutrons: 92,
            atomic_mass: 153.922209_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2275_f64,
            nuclear_spin: None,
        },
        ],
    }
}
