use super::super::{DecayMode, Element, Isotope};

pub fn element() -> Element {
    Element {
        symbol: "Yb",
        name: "Ytterbium",
        atomic_number: 70,
        atomic_mass: 173.045_f64,
        electronegativity: Some(1.1_f64),
        group: None,
        period: 6,
        category: "lanthanide",
        electron_configuration: "[Xe] 4f¹⁴ 6s²",
        isotopes: vec![
        Isotope {
            name: "Ytterbium-168",
            symbol: "¹⁶⁸Yb",
            mass_number: 168,
            neutrons: 98,
            atomic_mass: 167.933897_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.00123_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Ytterbium-169",
            symbol: "¹⁶⁹Yb",
            mass_number: 169,
            neutrons: 99,
            atomic_mass: 168.93519_f64,
            half_life: Some(32.018_f64),
            half_life_unit: Some("days"),
            stable: false,
            decay_modes: vec![
            DecayMode {
                mode: "electron capture",
                branching_ratio: 1.0_f64,
                daughter: Some("Thulium-169"),
            },
            ],
            natural_abundance: 0.0_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Ytterbium-170",
            symbol: "¹⁷⁰Yb",
            mass_number: 170,
            neutrons: 100,
            atomic_mass: 169.934762_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.02982_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Ytterbium-171",
            symbol: "¹⁷¹Yb",
            mass_number: 171,
            neutrons: 101,
            atomic_mass: 170.936327_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.1409_f64,
            nuclear_spin: Some("1/2-"),
        },
        Isotope {
            name: "Ytterbium-172",
            symbol: "¹⁷²Yb",
            mass_number: 172,
            neutrons: 102,
            atomic_mass: 171.936382_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.2168_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Ytterbium-173",
            symbol: "¹⁷³Yb",
            mass_number: 173,
            neutrons: 103,
            atomic_mass: 172.938211_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.16103_f64,
            nuclear_spin: Some("5/2-"),
        },
        Isotope {
            name: "Ytterbium-174",
            symbol: "¹⁷⁴Yb",
            mass_number: 174,
            neutrons: 104,
            atomic_mass: 173.938862_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.32026_f64,
            nuclear_spin: None,
        },
        Isotope {
            name: "Ytterbium-176",
            symbol: "¹⁷⁶Yb",
            mass_number: 176,
            neutrons: 106,
            atomic_mass: 175.942572_f64,
            half_life: None,
            half_life_unit: None,
            stable: true,
            decay_modes: vec![],
            natural_abundance: 0.12996_f64,
            nuclear_spin: None,
        },
        ],
    }
}
